"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, ArrowDown, ArrowDownRight, ArrowRight, ArrowUp, ArrowUpRight, BarChart3, CalendarDays, Camera, ChartNoAxesCombined, Check, CircleCheck, Clock3, FolderKanban, Globe, GripVertical, HardDrive, Headset, Hourglass, IndianRupee, Keyboard, LayoutGrid, MapPin, Megaphone, Monitor, Mouse, Network, Package, Plus, ShieldCheck, SlidersHorizontal, TrendingUp, TriangleAlert, UsersRound, WalletCards, X } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { calculateMetrics } from "../lib/engine";
import type { Store } from "../lib/schema";
import "./dashboard.css";

type Row = { id: string; [key: string]: any };
type Props = { store: Record<string, Row[]>; navigate: (id: string) => void; onAdd: (id: string) => void; branch: string; widgets: string[]; onWidgetsChange: (ids: string[]) => void; userName: string; userRole?: string; financialAvailable?: boolean };
type KPI = { title: string; value: string; full?: string; icon: typeof UsersRound; color: string; tint: string; module: string; change?: number; inverse?: boolean; caption: string; spark: number[]; count?: number };
const TODAY_ISO = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const TODAY = new Date(`${TODAY_ISO}T12:00:00+05:30`);
const COLORS = ["#0878ff", "#00c2c9", "#9a8aff", "#ffbf47", "#62a4fa", "#ec8cb6"];
const WIDGETS = [
  { id: "pipeline", name: "Lead pipeline", icon: UsersRound }, { id: "revenue", name: "Revenue vs expenses", icon: BarChart3 },
  { id: "cities", name: "Projects by city", icon: MapPin }, { id: "services", name: "Service profitability", icon: TrendingUp },
  { id: "projects", name: "Ongoing projects", icon: FolderKanban }, { id: "leads", name: "Recent leads", icon: UsersRound },
  { id: "visits", name: "Upcoming site visits", icon: CalendarDays }, { id: "inventory", name: "Inventory summary", icon: Package },
  { id: "trend", name: "Financial trend", icon: ChartNoAxesCombined }, { id: "operations", name: "Operations at a glance", icon: Activity },
];
const DEFAULT_WIDGETS = WIDGETS.map(w => w.id);

function value(row: Row | undefined, ...keys: string[]): any { if (!row) return ""; for (const key of keys) if (row[key] !== undefined && row[key] !== null && row[key] !== "") return row[key]; return ""; }
function number(row: Row | undefined, ...keys: string[]) { return Number(value(row, ...keys)) || 0; }
function text(row: Row | undefined, ...keys: string[]) { return String(value(row, ...keys) || ""); }
function money(amount: number, compact = false) { if (compact) { const abs = Math.abs(amount); if (abs >= 10000000) return `₹${(amount / 10000000).toFixed(2)}Cr`; if (abs >= 100000) return `₹${(amount / 100000).toFixed(2)}L`; if (abs >= 1000) return `₹${(amount / 1000).toFixed(1)}K`; } return `₹${Math.round(amount).toLocaleString("en-IN")}`; }
function formatDay(date: string, withMonth = true) { if (!date) return "—"; const parsed = new Date(date); return Number.isNaN(parsed.getTime()) ? "—" : parsed.toLocaleDateString("en-IN", withMonth ? { day: "2-digit", month: "short" } : { day: "2-digit" }); }
function monthKey(date: string) { return date?.slice(0, 7) || ""; }
function percentage(current: number, previous: number) { return previous ? Math.round(((current - previous) / previous) * 100) : current ? 100 : 0; }
function isClosed(status: string) { return /^(completed|work completed|cancelled|closed|resolved)$/i.test(status); }
function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(n => n[0]).join("").toUpperCase() || "?"; }
function categoryIcon(name: string) { const n = name.toLowerCase(); if (/cctv|camera/.test(n)) return Camera; if (/network|router|switch|cable/.test(n)) return Network; if (/web|domain|hosting/.test(n)) return Globe; if (/social|market|advert|campaign/.test(n)) return Megaphone; if (/keyboard/.test(n)) return Keyboard; if (/mouse/.test(n)) return Mouse; if (/dvr|nvr|ssd|hdd|usb|drive/.test(n)) return HardDrive; if (/software|antivirus|license|security/.test(n)) return ShieldCheck; if (/support|repair/.test(n)) return Headset; if (/desktop|laptop|monitor/.test(n)) return Monitor; return FolderKanban; }
function statusStyle(status: string) { const n = status.toLowerCase(); if (/completed|won|paid|on track|present|active/.test(n)) return { background: "#e4f8ef", color: "#0daa79" }; if (/hold|negotiat|survey|procurement|waiting|overdue/.test(n)) return { background: "#fff2df", color: "#e39a29" }; if (/lost|delay|cancel|critical/.test(n)) return { background: "#ffedf0", color: "#ee6874" }; if (/approval|testing|interested/.test(n)) return { background: "#f0eaff", color: "#8f67d9" }; return { background: "#eaf3ff", color: "#3480e8" }; }
function Sparkline({ values, color }: { values: number[]; color: string }) { const max = Math.max(...values, 1), min = Math.min(...values, 0); const points = values.map((v, i) => `${i * 10},${16 - ((v - min) / (max - min || 1)) * 14}`).join(" "); return <svg className="dash-kpi-spark" viewBox="0 0 50 18" aria-hidden="true"><polyline points={points} fill="none" stroke={color} strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function ChartTooltip({ active, payload, label }: any) { if (!active || !payload?.length) return null; return <div className="dash-chart-tooltip"><strong>{label}</strong>{payload.map((item: any) => <p key={item.dataKey}><span><i style={{ background: item.color }} />{item.name}</span><b>{money(Number(item.value), true)}</b></p>)}</div>; }
function Empty({ message, action, onClick }: { message: string; action?: string; onClick?: () => void }) { return <div className="dash-empty"><FolderKanban size={24} strokeWidth={1.4} /><span>{message}</span>{action && <button type="button" className="dash-button" onClick={onClick}><Plus size={12} />{action}</button>}</div>; }

export default function Dashboard({ store, navigate, onAdd, branch, widgets, onWidgetsChange, userName, userRole = "Admin", financialAvailable }: Props) {
  const canSeeFinance = financialAvailable ?? !["Technician", "Inventory", "Client", "Sales", "Developer", "Marketing"].includes(userRole);
  const allowedDefinitions = WIDGETS.filter(w => canSeeFinance || !["revenue", "services", "trend"].includes(w.id));
  const [range, setRange] = useState(6);
  const [trendRange, setTrendRange] = useState(6);
  const [customize, setCustomize] = useState(false);
  const [quickOpen, setQuickOpen] = useState(false);
  const [showMetrics, setShowMetrics] = useState(false);
  const [dragged, setDragged] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState<string | null>(null);
  const [sizes, setSizes] = useState<Record<string, string>>({});
  useEffect(() => { try { setSizes(JSON.parse(localStorage.getItem("itsss-dashboard-sizes") || "{}")); } catch { /* Start with the standard layout. */ } }, []);
  useEffect(() => { if (!customize && !quickOpen) return; const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setCustomize(false); setQuickOpen(false); } }; document.addEventListener("keydown", onKey); return () => document.removeEventListener("keydown", onKey); }, [customize, quickOpen]);
  const enabled = (widgets || DEFAULT_WIDGETS).filter(id => allowedDefinitions.some(w => w.id === id));
  const resize = (id: string, size: string) => { const next = { ...sizes, [id]: size }; setSizes(next); try { localStorage.setItem("itsss-dashboard-sizes", JSON.stringify(next)); } catch { /* The current layout still works without browser storage. */ } };
  const updateWidgets = (ids: string[]) => onWidgetsChange(ids);
  const reorder = (from: string, target: string) => { if (from === target) return; const next = enabled.filter(id => id !== from); next.splice(next.indexOf(target), 0, from); updateWidgets(next); };

  const data = useMemo(() => {
    const all = (id: string, ...aliases: string[]) => (store[id] || aliases.map(alias => store[alias]).find(Boolean) || []).filter(r => !r.deleted && !r.deletedAt && !r.archived && !r.archivedAt && !r._deleted);
    const sites = all("sites"), customers = all("customers"), products = all("products"), serviceCatalog = all("services"), projectRows = all("projects"), employeeRows = all("employees");
    const find = (rows: Row[], id: string) => rows.find(row => String(row.id) === String(id));
    const city = (row: Row) => text(row, "city", "branch") || text(find(sites, text(row, "site", "siteId")), "city", "branch") || text(find(customers, text(row, "customer", "customerId")), "city", "branch") || text(find(projectRows, text(row, "project", "projectId")), "city", "branch") || text(find(employeeRows, text(row, "employee", "technician", "assignedTo")), "city", "branch") || "Other";
    const scoped = (rows: Row[]) => !branch || ["all", "all branches"].includes(branch.toLowerCase()) ? rows : rows.filter(r => city(r) === "Other" || city(r).toLowerCase() === branch.toLowerCase() || text(r, "location").toLowerCase() === branch.toLowerCase());
    const leads = scoped(all("leads"));
    const projects = scoped(projectRows).filter(p => p.status !== "Cancelled");
    const expenses = [...scoped(all("expenses")), ...scoped(all("employeeExpenses"))].filter(e => e.approvalStatus === "Approved" || ["Approved", "Paid", "Reimbursed"].includes(e.status));
    const payments = [...scoped(all("payments")), ...scoped(all("income"))].filter(p => p.status === "Received");
    const inventory = scoped(all("inventory"));
    const activeProjects = projects.filter(row => !isClosed(text(row, "status")) && row.status !== "On Hold");
    const projectName = (row: Row) => text(row, "name", "projectName", "title") || "Untitled project";
    const customerName = (row: Row) => text(find(customers, text(row, "customer", "customerId")), "company", "companyName", "name", "customerName") || text(row, "customerName", "company", "companyName", "customer") || "—";
    const tasks = all("tasks");
    const expenseValue = (row: Row) => number(row, "amount", "total", "cost");
    const paymentValue = (row: Row) => (row.type === "Refund" ? -1 : 1) * number(row, "amount", "total", "paymentAmount");
    const paymentDate = (row: Row) => text(row, "date", "paymentDate", "receivedDate", "createdAt");
    const expenseDate = (row: Row) => text(row, "date", "expenseDate", "createdAt");
    const projectRevenue = (row: Row) => number(row, "value", "projectValue", "revenue", "amount", "budget");
    const projectCost = (row: Row) => number(row, "actualCost", "cost");
    const serviceName = (row: Row) => text(find(serviceCatalog, text(row, "service")), "name") || text(row, "type", "projectType", "category", "requiredService") || "Other services";
    const leadService = (row: Row) => text(find(serviceCatalog, text(row, "service")), "name", "category") || text(find(products, text(row, "product")), "name", "category") || text(row, "requiredService", "productService", "type") || "—";
    const months = Array.from({ length: 12 }, (_, i) => { const date = new Date(TODAY.getFullYear(), TODAY.getMonth() - 11 + i, 1); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; const revenue = payments.filter(p => monthKey(paymentDate(p)) === key).reduce((s, p) => s + paymentValue(p), 0); const spent = expenses.filter(e => monthKey(expenseDate(e)) === key).reduce((s, e) => s + expenseValue(e), 0); return { month: date.toLocaleDateString("en-IN", { month: "short" }), key, revenue, expenses: spent, profit: revenue - spent, leads: leads.filter(l => monthKey(text(l, "createdAt", "date", "createdDate")) === key).length, projects: projects.filter(p => monthKey(text(p, "startDate", "createdAt")) === key).length }; });
    const current = months.at(-1)!, previous = months.at(-2)!;
    const citiesMap: Record<string, number> = {}; projects.forEach(p => { const c = city(p); citiesMap[c] = (citiesMap[c] || 0) + 1; });
    const cities = Object.entries(citiesMap).sort((a, b) => b[1] - a[1]).map(([name, count], i) => ({ name, value: count, color: COLORS[i % COLORS.length] }));
    const groups: Record<string, { revenue: number; cost: number }> = {};
    projects.forEach(p => { const key = serviceName(p); if (!groups[key]) groups[key] = { revenue: 0, cost: 0 }; groups[key].revenue += projectRevenue(p); groups[key].cost += projectCost(p); });
    const services = Object.entries(groups).map(([name, numbers]) => ({ name, revenue: numbers.revenue, margin: numbers.revenue ? Math.round((numbers.revenue - numbers.cost) / numbers.revenue * 100) : 0 })).sort((a, b) => b.revenue - a.revenue).slice(0, 6);
    const pipelineStages = [ { name: "New leads", match: /^(new|new lead)$/i, color: "#0878ff" }, { name: "Contacted", match: /^contacted$/i, color: "#04bf9a" }, { name: "Qualified", match: /interested|requirement/i, color: "#16bce6" }, { name: "Site survey", match: /survey|visit/i, color: "#9b79ef" }, { name: "Negotiation", match: /negotiation|follow-up/i, color: "#ffb329" }, { name: "Won", match: /^won|converted$/i, color: "#04b685" } ];
    const pipeline = pipelineStages.map(s => ({ ...s, count: leads.filter(l => s.match.test(text(l, "status", "leadStatus"))).length }));
    const won = leads.filter(l => /^won|converted$/i.test(text(l, "status", "leadStatus"))).length;
    const dateKey = (row: Row) => text(row, "date", "surveyDate", "scheduledDate", "scheduledAt", "startAt", "dueAt", "startDate");
    const visitRows = [ ...scoped(all("surveys", "siteSurveys")).map(r => ({ ...r, _module: "surveys", _kind: "Site survey" })), ...scoped(all("technicianJobs", "jobs")).map(r => ({ ...r, _module: "technicianJobs", _kind: "Installation" })), ...scoped(all("workOrders", "work-orders", "workorders")).map(r => ({ ...r, _module: "workOrders", _kind: "Service visit" })) ];
    const visits = visitRows.filter(r => dateKey(r).slice(0, 10) >= TODAY_ISO && !isClosed(text(r, "status"))).sort((a, b) => `${dateKey(a)} ${text(a, "time", "startTime")}`.localeCompare(`${dateKey(b)} ${text(b, "time", "startTime")}`));
    const stock = inventory.map(r => { const product = find(products, text(r, "product", "productId")); const quantity = value(r, "available", "availableStock") !== "" ? number(r, "available", "availableStock") : Math.max(0, number(r, "quantity", "stock", "inStock") - number(r, "reserved") - number(r, "damaged")); const minimum = value(r, "minimumStock", "minStock", "reorderLevel") !== "" ? number(r, "minimumStock", "minStock", "reorderLevel") : number(product, "minimumStock", "minStock", "reorderLevel"); const label = text(product, "name", "productName") || text(r, "name", "productName", "product") || "Product"; return { ...r, label, quantity, minimum, price: number(r, "unitCost", "purchasePrice", "cost") || number(product, "purchasePrice", "cost", "price"), low: quantity <= minimum }; });
    const allRevenue = payments.reduce((s, p) => s + paymentValue(p), 0);
    const projectBalances = projects.filter(p => p.status !== "Cancelled").map(p => ({ ...p, balance: Math.max(0, projectRevenue(p) - payments.filter(pay => text(pay, "project", "projectId") === String(p.id)).reduce((s, pay) => s + paymentValue(pay), 0)) }));
    const receivables = scoped(all("receivables")).filter(r => !r.project).map(r => ({ ...r, balance: value(r, "balance") !== "" ? number(r, "balance") : Math.max(0, number(r, "amount") - number(r, "paid")) }));
    const pendingRecords = [...projectBalances, ...receivables].filter(p => p.balance > 0);
    const outstanding = pendingRecords.reduce((sum, p) => sum + p.balance, 0);
    const progress = (project: Row) => { if (value(project, "progress", "progressPercentage") !== "") return Math.max(0, Math.min(100, number(project, "progress", "progressPercentage"))); const linked = tasks.filter(t => text(t, "project", "projectId") === String(project.id)); if (linked.length) return Math.round(linked.reduce((s, t) => s + (isClosed(text(t, "status")) ? 100 : number(t, "progress", "progressPercentage")), 0) / linked.length); const status = text(project, "status").toLowerCase(); return ({ planning: 10, "material procurement": 20, "material ready": 35, "installation scheduled": 40, "installation in progress": 60, testing: 80, "customer approval": 90, completed: 100 } as Record<string, number>)[status] || 0; };
    const attendance = scoped(all("attendance")).filter(a => text(a, "date", "attendanceDate").slice(0, 10) === TODAY_ISO);
    const contracts = [...scoped(all("amc")), ...scoped(all("licenses")), ...scoped(all("domains")), ...scoped(all("hosting"))];
    const renewals = contracts.filter(r => { const date = new Date(text(r, "endDate", "expiryDate", "hostingExpiry", "expiry")); const days = (date.getTime() - TODAY.getTime()) / 86400000; return days >= -1 && days <= 30 && !["Cancelled", "Renewed"].includes(r.status); });
    const metricStore = { ...store, leads, projects, payments: scoped(all("payments")), expenses: scoped(all("expenses")), income: scoped(all("income")), employeeExpenses: scoped(all("employeeExpenses")), inventory, employees: scoped(employeeRows), attendance, followups: scoped(all("followups")), tickets: scoped(all("tickets")), workOrders: scoped(all("workOrders")), technicianJobs: scoped(all("technicianJobs")), receivables: scoped(all("receivables")), amc: scoped(all("amc")), licenses: scoped(all("licenses")), domains: scoped(all("domains")), hosting: scoped(all("hosting")), purchases: scoped(all("purchases")) } as Store;
    const metrics = calculateMetrics(metricStore, TODAY);
    return { metrics, leads, projects, expenses, payments, activeProjects, months, current, previous, cities, services, pipeline, won, visits, stock, lowStock: stock.filter(s => s.low).length, allRevenue, outstanding, pendingRecords, customerName, projectName, leadService, city, progress, dateKey, inventoryValue: stock.reduce((sum, s) => sum + (value(s, "value") !== "" ? number(s, "value") : s.quantity * s.price), 0), attendance, employees: scoped(employeeRows), tickets: scoped(all("tickets", "support")).filter(r => !isClosed(text(r, "status"))), followups: scoped(all("followups", "follow-ups")).filter(r => text(r, "dueAt", "date", "nextFollowup", "nextFollowUpDate", "dueDate") && text(r, "dueAt", "date", "nextFollowup", "nextFollowUpDate", "dueDate").slice(0, 10) <= TODAY_ISO && r.status === "Scheduled"), renewals, purchases: scoped(all("purchases")) };
  }, [store, branch]);

  const financialKpis: KPI[] = [
    { title: "Total leads", value: String(data.leads.length), icon: UsersRound, color: "#0878ff", tint: "#eaf3ff", module: "leads", change: percentage(data.current.leads, data.previous.leads), caption: "vs. last month", spark: data.months.slice(-6).map(m => m.leads) },
    { title: "Active projects", value: String(data.activeProjects.length), icon: FolderKanban, color: "#0cb891", tint: "#e8f8f2", module: "projects", change: percentage(data.current.projects, data.previous.projects), caption: "vs. last month", spark: data.months.slice(-6).map(m => m.projects) },
    { title: "Monthly revenue", value: money(data.current.revenue, true), full: money(data.current.revenue), icon: IndianRupee, color: "#00b5be", tint: "#e8f8fa", module: "payments", change: percentage(data.current.revenue, data.previous.revenue), caption: "vs. last month", spark: data.months.slice(-6).map(m => m.revenue) },
    { title: "Monthly expenses", value: money(data.current.expenses, true), full: money(data.current.expenses), icon: WalletCards, color: "#f47687", tint: "#ffedf0", module: "expenses", change: percentage(data.current.expenses, data.previous.expenses), inverse: true, caption: "vs. last month", spark: data.months.slice(-6).map(m => m.expenses) },
    { title: "Net profit", value: money(data.metrics.netProfit, true), full: money(data.metrics.netProfit), icon: TrendingUp, color: "#9069ed", tint: "#f1ebff", module: "reports", caption: "Across all projects", spark: data.months.slice(-6).map(m => m.profit) },
    { title: "Outstanding", value: money(data.outstanding, true), full: money(data.outstanding), icon: Hourglass, color: "#eba52b", tint: "#fff6e5", module: "receivables", count: data.pendingRecords.length, caption: data.pendingRecords.length ? "pending payments" : "project balance", spark: data.months.slice(-6).map(m => m.revenue) },
  ];
  const kpis: KPI[] = canSeeFinance ? financialKpis : [
    financialKpis[0], financialKpis[1],
    { title: "Open tickets", value: String(data.metrics.openTickets), icon: Headset, color: "#00b5be", tint: "#e8f8fa", module: "tickets", caption: "Awaiting resolution", spark: [] },
    { title: "Follow-ups due", value: String(data.metrics.followupsDue), icon: Clock3, color: "#f47687", tint: "#ffedf0", module: "followups", caption: "Keep customers connected", spark: [] },
    { title: "Low stock alerts", value: String(data.metrics.lowStock), icon: Package, color: "#9069ed", tint: "#f1ebff", module: "inventory", caption: "Ready to reorder", spark: [] },
    { title: "Team attendance", value: `${data.metrics.attendanceToday}/${data.employees.length}`, icon: UsersRound, color: "#eba52b", tint: "#fff6e5", module: "attendance", caption: "Present or on site today", spark: [] },
  ];
  const widgetHead = (id: string, children?: ReactNode) => { const definition = WIDGETS.find(w => w.id === id)!; const Icon = definition.icon; return <div className={`dash-widget-head ${id === "trend" ? "dash-trend-head" : ""}`}><div className="dash-widget-title">{customize && <button type="button" className="dash-drag-grip" title="Drag to rearrange" aria-label={`Drag ${definition.name}`}><GripVertical size={12} /></button>}<Icon size={15} strokeWidth={2.2} /><h3>{definition.name}</h3></div>{children && <div className="dash-widget-tools">{children}</div>}</div>; };
  const chartLegend = (profit = false) => <div className="dash-chart-legend"><span><i style={{ background: "#0878ff" }} />{profit ? "Collections" : "Revenue"}</span><span><i style={{ background: "#00c2c9" }} />{profit ? "Costs" : "Expenses"}</span>{profit && <span><i style={{ background: "#9775ef" }} />Surplus</span>}</div>;
  const viewAll = (id: string) => <button type="button" className="dash-widget-link" onClick={() => navigate(id)}>View all<ArrowUpRight size={10} /></button>;
  const widgetBody = (id: string): ReactNode => {
    if (id === "pipeline") return <>{widgetHead(id, <span className="dash-widget-total"><b>{data.leads.length}</b>leads</span>)}<div className="dash-pipeline"><div className="dash-funnel">{data.pipeline.map((stage, i) => <div className="dash-funnel-step" key={stage.name} style={{ background: stage.color, width: `${100 - i * 12}%` }} />)}</div><div className="dash-pipeline-labels">{data.pipeline.map(stage => <button type="button" key={stage.name} onClick={() => navigate("leads")}><span><i style={{ background: stage.color }} />{stage.name}</span><b>{stage.count}<em>({data.leads.length ? Math.round(stage.count / data.leads.length * 100) : 0}%)</em></b></button>)}</div></div><div className="dash-pipeline-foot"><span>Conversion rate</span><b>{data.leads.length ? (data.won / data.leads.length * 100).toFixed(1) : 0}%<ArrowUpRight size={10} style={{ display: "inline", marginLeft: 3 }} /></b></div></>;
    if (id === "revenue") return <>{widgetHead(id, <select className="dash-select" aria-label="Revenue chart period" value={range} onChange={e => setRange(Number(e.target.value))}><option value={3}>Last 3 months</option><option value={6}>Last 6 months</option><option value={12}>Last 12 months</option></select>)}{chartLegend()}<div className="dash-revenue-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.months.slice(-range)} margin={{ top: 11, right: 1, left: -16, bottom: 0 }} barGap={4}><CartesianGrid stroke="#edf1f7" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 8, fill: "#8392a9" }} dy={4} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 7, fill: "#91a0b6" }} width={45} tickFormatter={v => v ? money(v, true) : "0"} /><Tooltip cursor={{ fill: "#f3f7ff" }} content={<ChartTooltip />} /><Bar dataKey="revenue" name="Revenue" fill="#0878ff" radius={[3, 3, 0, 0]} maxBarSize={17} /><Bar dataKey="expenses" name="Expenses" fill="#00c2c9" radius={[3, 3, 0, 0]} maxBarSize={17} /></BarChart></ResponsiveContainer></div><div className="dash-pipeline-foot"><span>Revenue this month</span><b style={{ color: "#0878ff" }}>{money(data.current.revenue)}</b></div></>;
    if (id === "cities") return <>{widgetHead(id)}{data.cities.length ? <><div className="dash-city-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.cities} dataKey="value" nameKey="name" innerRadius="61%" outerRadius="85%" startAngle={90} endAngle={-270} paddingAngle={2} stroke="none">{data.cities.map(c => <Cell key={c.name} fill={c.color} />)}</Pie><Tooltip formatter={(v: any, name: any) => [`${v} projects`, name]} contentStyle={{ fontSize: 10, borderRadius: 8, borderColor: "#e3eaf4" }} /></PieChart></ResponsiveContainer><div className="dash-city-center"><b>{data.projects.length}</b><span>total projects</span></div></div><div className="dash-city-legend">{data.cities.slice(0, 6).map(c => <span key={c.name}><i style={{ background: c.color }} />{c.name}<b>{c.value}</b></span>)}</div></> : <Empty message="City insights appear with your first project." />}</>;
    if (id === "services") return <>{widgetHead(id)}{data.services.length ? <><div className="dash-service-list">{data.services.map((service, i) => <button type="button" className="dash-service" key={service.name} onClick={() => navigate("reports")} title={`${service.name}: ${money(service.revenue)} revenue, ${service.margin}% margin`}><span className="dash-service-label">{service.name}</span><span className="dash-service-track"><i style={{ width: `${Math.min(100, Math.max(service.margin, 0))}%`, background: COLORS[i % COLORS.length] }} /></span><b>{service.margin}%</b></button>)}</div><div className="dash-service-caption"><CircleCheck size={10} />Margin based on project costs</div></> : <Empty message="Project revenue and costs reveal your margins." />}</>;
    if (id === "projects") return <>{widgetHead(id, viewAll("projects"))}{data.activeProjects.length ? <div className="dash-table-wrap dash-table-scroll"><table className="dash-table dash-table-projects"><thead><tr><th>Project / client</th><th>City</th><th>Progress</th><th>Status</th><th>Due date</th></tr></thead><tbody>{data.activeProjects.slice(0, 4).map((project, i) => { const Icon = categoryIcon(text(project, "type", "name", "projectName")); const progress = data.progress(project); const due = text(project, "expectedCompletionDate", "dueDate", "endDate"); const overdue = due && due.slice(0, 10) < TODAY_ISO; const state = overdue ? "Delayed" : progress >= 75 ? "On track" : text(project, "status") || "Planning"; return <tr key={project.id || i} onClick={() => navigate("projects")} onKeyDown={e => { if (e.key === "Enter") navigate("projects"); }} tabIndex={0}><td><div className="dash-table-name"><span className="dash-record-icon" style={{ background: `${COLORS[i]}15`, color: COLORS[i] }}><Icon size={15} /></span><span><b>{data.projectName(project)}</b><small>{data.customerName(project)}</small></span></div></td><td>{data.city(project)}</td><td><div className="dash-progress"><span><i style={{ background: progress >= 75 ? "#08b78d" : "#0878ff", width: `${progress}%` }} /></span>{progress}%</div></td><td><span className="dash-status" style={statusStyle(state)}><i />{state.replace("Installation ", "").replace("Material ", "")}</span></td><td style={{ color: overdue ? "#ee7a82" : undefined }}>{formatDay(due)}</td></tr>; })}</tbody></table></div> : <Empty message="Ready for your next big project?" action="Create project" onClick={() => onAdd("projects")} />}</>;
    if (id === "leads") return <>{widgetHead(id, viewAll("leads"))}{data.leads.length ? <div className="dash-table-wrap dash-table-scroll"><table className="dash-table dash-table-leads"><thead><tr><th>Name / company</th><th>Service</th><th>City</th><th>Status</th></tr></thead><tbody>{[...data.leads].sort((a, b) => text(b, "createdAt", "date").localeCompare(text(a, "createdAt", "date"))).slice(0, 4).map((lead, i) => { const name = text(lead, "name", "leadName", "contactPerson") || "New lead"; return <tr key={lead.id || i} onClick={() => navigate("leads")} onKeyDown={e => { if (e.key === "Enter") navigate("leads"); }} tabIndex={0}><td><div className="dash-table-name"><span className="dash-avatar" style={{ background: `${COLORS[i % COLORS.length]}15`, color: COLORS[i % COLORS.length] }}>{initials(name)}</span><span><b>{name}</b><small>{text(lead, "company", "companyName") || "Individual"}</small></span></div></td><td>{data.leadService(lead).replace("Installation", "").replace("Development", "Dev.") || "—"}</td><td>{data.city(lead)}</td><td><span className="dash-status" style={statusStyle(text(lead, "status", "leadStatus"))}>{text(lead, "status", "leadStatus").replace("Site Survey ", "Survey ") || "New"}</span></td></tr>; })}</tbody></table></div> : <Empty message="Every great partnership starts with a lead." action="Add lead" onClick={() => onAdd("leads")} />}</>;
    if (id === "visits") return <>{widgetHead(id, viewAll("calendar"))}{data.visits.length ? <><div className="dash-visit-list">{data.visits.slice(0, 4).map((visit, i) => { const time = text(visit, "time", "startTime", "scheduledTime") || (data.dateKey(visit).includes("T") ? new Date(data.dateKey(visit)).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: true }) : "All day"); const site = (store.sites || []).find(s => String(s.id) === text(visit, "site", "siteId")); const Icon = categoryIcon(text(visit, "type", "description", "requirement", "name")); return <button type="button" className="dash-visit" key={`${visit._module}-${visit.id || i}`} onClick={() => navigate(visit._module)}><span className="dash-visit-time">{time}<small>{data.dateKey(visit).slice(0, 10) === TODAY_ISO ? "Today" : formatDay(data.dateKey(visit))}</small></span><span className="dash-visit-icon" style={{ background: `${COLORS[i]}13`, color: COLORS[i] }}><Icon size={13} /></span><span className="dash-visit-info"><b>{text(site, "name", "siteName") || data.customerName(visit)}</b><span>{text(visit, "name", "jobDescription", "description", "requirement") || visit._kind} · {data.city(visit)}</span></span></button>; })}</div><div className="dash-visit-footer"><Clock3 size={11} />{data.visits.filter(v => data.dateKey(v).slice(0, 10) === TODAY_ISO).length} visits scheduled for today</div></> : <Empty message="Your schedule is clear. Plan your next visit." action="Schedule visit" onClick={() => onAdd("surveys")} />}</>;
    if (id === "inventory") return <>{widgetHead(id, viewAll("inventory"))}{data.stock.length ? <><div className="dash-inventory-items">{data.stock.slice(0, 6).map((item, i) => { const Icon = categoryIcon(item.label); return <button type="button" className="dash-inventory-item" key={item.id || i} onClick={() => navigate("inventory")} title={`${item.label}: ${item.quantity} available, minimum ${item.minimum}`}><Icon size={21} strokeWidth={1.8} /><span>{item.label.replace(/^(Hikvision|Dahua|TP-Link|Logitech|SanDisk|Microsoft|Quick Heal)\s/i, "").replace(/\s\d+.*$/, "")}</span><b>{item.quantity.toLocaleString("en-IN")}</b><small className={item.low ? "dash-low-stock" : ""}><i />{item.low ? "Low stock" : "In stock"}</small></button>; })}</div><div className="dash-inventory-footer"><span>{canSeeFinance ? "Total inventory value" : "Available stock"} <b>{canSeeFinance ? money(data.inventoryValue, true) : data.stock.reduce((total, item) => total + item.quantity, 0).toLocaleString("en-IN")}</b></span><button type="button" onClick={() => navigate("inventory")}><TriangleAlert size={10} />{data.lowStock} low stock {data.lowStock === 1 ? "item" : "items"}<ArrowRight size={10} /></button></div></> : <Empty message="Keep every product, location and quantity in view." action="Add stock" onClick={() => onAdd("inventory")} />}</>;
    if (id === "trend") return <>{widgetHead(id, <>{chartLegend(true)}<select className="dash-select" aria-label="Financial trend period" value={trendRange} onChange={e => setTrendRange(Number(e.target.value))}><option value={3}>Last 3 months</option><option value={6}>Last 6 months</option><option value={12}>Last 12 months</option></select></>)}<div className="dash-trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.months.slice(-trendRange)} margin={{ top: 20, right: 5, left: -16, bottom: 0 }}><defs><linearGradient id="dash-revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0878ff" stopOpacity={0.13} /><stop offset="100%" stopColor="#0878ff" stopOpacity={0} /></linearGradient><linearGradient id="dash-profit-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9775ef" stopOpacity={0.12} /><stop offset="100%" stopColor="#9775ef" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="#edf1f7" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 8, fill: "#8392a9" }} dy={3} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 7, fill: "#91a0b6" }} width={45} tickFormatter={v => v ? money(v, true) : "0"} /><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="revenue" name="Revenue" stroke="#0878ff" fill="url(#dash-revenue-fill)" strokeWidth={1.8} dot={{ r: 2.5, fill: "#0878ff", strokeWidth: 0 }} /><Area type="monotone" dataKey="expenses" name="Expenses" stroke="#00c2c9" fill="transparent" strokeWidth={1.5} dot={{ r: 2.5, fill: "#00c2c9", strokeWidth: 0 }} /><Area type="monotone" dataKey="profit" name="Monthly surplus" stroke="#9775ef" fill="url(#dash-profit-fill)" strokeWidth={1.5} dot={{ r: 2.5, fill: "#9775ef", strokeWidth: 0 }} /></AreaChart></ResponsiveContainer></div><div className="dash-trend-meta"><span>Keep a pulse on your business performance.</span><b>{data.current.revenue ? Math.round(data.current.profit / data.current.revenue * 100) : 0}% collection surplus this month</b></div></>;
    if (id === "operations") {
      const business = data.metrics;
      const metrics = [
        { name: "Follow-ups due", number: business.followupsDue, icon: Clock3, module: "followups" },
        { name: "Open support tickets", number: business.openTickets, icon: Headset, module: "tickets" },
        { name: "Upcoming renewals", number: business.amcRenewals + business.licenseRenewals + business.domainRenewals + business.hostingRenewals, icon: ShieldCheck, module: "amc" },
        { name: "Team attendance", number: `${business.attendanceToday}/${data.employees.length}`, icon: UsersRound, module: "attendance" },
        { name: "Completed projects", number: business.completedProjects, icon: CircleCheck, module: "projects" },
        { name: "Hot leads", number: business.hotLeads, icon: TrendingUp, module: "leads" },
        ...(showMetrics ? [
          { name: "New leads today", number: business.newLeadsToday, icon: UsersRound, module: "leads" },
          { name: "Leads won", number: business.leadsWon, icon: CircleCheck, module: "leads" },
          { name: "Leads lost", number: business.leadsLost, icon: UsersRound, module: "leads" },
          { name: "Lead conversion", number: `${business.conversionRate}%`, icon: TrendingUp, module: "reports" },
          { name: "Delayed projects", number: business.delayedProjects, icon: TriangleAlert, module: "projects" },
          { name: "Projects on hold", number: business.projectsOnHold, icon: Hourglass, module: "projects" },
          { name: "Awaiting material", number: business.projectsAwaitingMaterial, icon: Package, module: "projects" },
          { name: "Upcoming site visits", number: data.visits.length, icon: MapPin, module: "workOrders" },
          { name: "Technicians on site", number: business.techniciansOnSite, icon: Activity, module: "technicianJobs" },
          { name: "Total sales", number: money(business.totalSales, true), icon: IndianRupee, module: "reports" },
          { name: "Gross profit", number: money(business.grossProfit, true), icon: TrendingUp, module: "reports" },
          { name: "Business net profit", number: money(business.netProfit, true), icon: TrendingUp, module: "reports" },
          { name: "Payments received", number: money(business.paymentsReceived, true), icon: WalletCards, module: "payments" },
          { name: "Purchase amount", number: money(business.purchaseAmount, true), icon: Package, module: "purchases" },
          { name: "Inventory value", number: money(business.inventoryValue, true), icon: Package, module: "inventory" },
          { name: "Low stock alerts", number: business.lowStock, icon: TriangleAlert, module: "inventory" },
          { name: "AMC renewals", number: business.amcRenewals, icon: ShieldCheck, module: "amc" },
          { name: "License renewals", number: business.licenseRenewals, icon: ShieldCheck, module: "licenses" },
          { name: "Domain renewals", number: business.domainRenewals, icon: Globe, module: "domains" },
          { name: "Hosting renewals", number: business.hostingRenewals, icon: Globe, module: "hosting" },
          { name: "Monthly recurring", number: money(business.recurringMRR, true), icon: IndianRupee, module: "recurring" },
          { name: "Annual recurring", number: money(business.recurringARR, true), icon: IndianRupee, module: "recurring" },
          { name: "Product performance", number: business.productStats.reduce((sum, product) => sum + product.units, 0), icon: Package, module: "reports" },
          { name: "Technician workload", number: business.technicianStats.reduce((sum, tech) => sum + tech.active, 0), icon: Activity, module: "technicianJobs" },
        ] : []),
      ];
      return <>{widgetHead(id, <button type="button" className="dash-widget-link" onClick={() => setShowMetrics(!showMetrics)}>{showMetrics ? "Show less" : "See all metrics"}<ArrowRight size={10} /></button>)}<div className={`dash-operations ${showMetrics ? "dash-operations-expanded" : ""}`}>{metrics.filter(m => canSeeFinance || typeof m.number !== "string" || !m.number.includes("₹")).map(m => <button type="button" className="dash-operation" key={m.name} onClick={() => navigate(m.module)}><m.icon /><span><b>{m.number}</b>{m.name}</span></button>)}</div></>;
    }
    return null;
  };

  return <div className="dash-root">
    <div className="dash-heading"><div><div className="dash-eyebrow"><span />YOUR BUSINESS, AT A GLANCE</div><h1>Welcome back, {userName?.split(" ")[0] || "Rohit"}! <span aria-hidden="true">👋</span></h1><p>Here&apos;s what&apos;s happening at ITSSS today.</p></div><div className="dash-heading-actions"><div className="dash-date"><CalendarDays size={14} />{TODAY.toLocaleDateString("en-IN", { weekday: "short", day: "2-digit", month: "short", year: "numeric" })}</div><button type="button" className="dash-button" onClick={() => setCustomize(true)} title="Customize dashboard"><SlidersHorizontal size={13} /><span className="dash-customize-label">Customize</span></button><button type="button" className="dash-button dash-button-primary" onClick={() => setQuickOpen(!quickOpen)} aria-expanded={quickOpen}><Plus size={14} />Quick action<ArrowDown size={11} /></button>{quickOpen && <><div style={{ position: "fixed", inset: 0, zIndex: 20 }} onClick={() => setQuickOpen(false)} /><div className="dash-action-menu">{[{ id: "leads", name: "Add lead", icon: UsersRound }, { id: "projects", name: "Create project", icon: FolderKanban }, { id: "expenses", name: "Add expense", icon: WalletCards }, { id: "payments", name: "Record payment", icon: IndianRupee }, { id: "tickets", name: "Create support ticket", icon: Headset }, { id: "surveys", name: "Schedule site visit", icon: MapPin }].map(a => <button type="button" key={a.id} onClick={() => { onAdd(a.id); setQuickOpen(false); }}><a.icon size={14} />{a.name}</button>)}</div></>}</div></div>
    <div className="dash-kpis">{kpis.map(kpi => { const isNegative = kpi.change !== undefined && (kpi.inverse ? kpi.change > 0 : kpi.change < 0); const ChangeIcon = kpi.change !== undefined && kpi.change < 0 ? ArrowDownRight : ArrowUpRight; return <button type="button" className="dash-kpi" key={kpi.title} onClick={() => navigate(kpi.module)} title={kpi.full || `${kpi.title}: ${kpi.value}`}><div className="dash-kpi-top"><span className="dash-kpi-label">{kpi.title}</span><span className="dash-kpi-icon" style={{ color: kpi.color, background: kpi.tint }}><kpi.icon size={18} strokeWidth={1.9} /></span></div><div className="dash-kpi-value">{kpi.value}</div><div className="dash-kpi-meta">{kpi.change !== undefined ? <><b className={isNegative ? "dash-negative" : ""}><ChangeIcon size={10} />{Math.abs(kpi.change)}%</b><span>{kpi.caption}</span></> : <>{kpi.count !== undefined && <b style={{ color: kpi.color }}>{kpi.count}</b>}<span>{kpi.caption}</span></>}</div><Sparkline values={kpi.spark} color={kpi.color} /></button>; })}</div>
    <div className="dash-section-label"><h2>Business overview</h2><span><i />Live workspace data</span></div>
    <div className="dash-widgets">{enabled.map(id => <section key={id} className={`dash-widget dash-widget-${id} ${sizes[id] === "wide" ? "dash-widget-wide" : ""} ${dragOver === id ? "dash-drag-over" : ""}`} aria-label={WIDGETS.find(w => w.id === id)?.name} draggable onDragStart={e => { setDragged(id); e.dataTransfer.setData("text/plain", id); e.dataTransfer.effectAllowed = "move"; }} onDragOver={e => { e.preventDefault(); if (dragged !== id) setDragOver(id); }} onDrop={e => { e.preventDefault(); const source = e.dataTransfer.getData("text/plain"); if (enabled.includes(source)) reorder(source, id); setDragged(null); setDragOver(null); }} onDragEnd={() => { setDragged(null); setDragOver(null); }}>{widgetBody(id)}</section>)}</div>
    {!enabled.length && <div className="dash-live-empty">Make this space your own. Choose the insights that matter to you.<br /><button type="button" className="dash-button dash-button-primary" onClick={() => setCustomize(true)}><LayoutGrid size={13} />Add dashboard widgets</button></div>}
    <div className="dash-footer"><span><ShieldCheck size={11} />Your workspace is up to date.</span><span>ITSSS · IT Smart Solution and Services</span></div>
    {customize && <div className="dash-dialog-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) setCustomize(false); }}><div className="dash-dialog" role="dialog" aria-modal="true" aria-labelledby="dash-customize-title"><div className="dash-dialog-heading"><div><h2 id="dash-customize-title">Your dashboard, your way</h2><p>Choose your widgets, adjust their size, and arrange your view.<br />Drag dashboard cards to rearrange them anytime.</p></div><button type="button" className="dash-dialog-close" onClick={() => setCustomize(false)} aria-label="Close customization"><X size={17} /></button></div><div className="dash-custom-list">{[...enabled, ...allowedDefinitions.map(w => w.id).filter(id => !enabled.includes(id))].map(id => { const definition = WIDGETS.find(w => w.id === id)!; const index = enabled.indexOf(id), checked = index >= 0; return <div className={`dash-custom-item ${checked ? "dash-custom-enabled" : ""}`} key={id} draggable={checked} onDragStart={e => e.dataTransfer.setData("text/plain", id)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const source = e.dataTransfer.getData("text/plain"); if (enabled.includes(source) && checked) reorder(source, id); }}><GripVertical size={13} /><label className="dash-custom-check"><input type="checkbox" checked={checked} onChange={() => updateWidgets(checked ? enabled.filter(w => w !== id) : [...enabled, id])} />{definition.name}</label>{checked && <><select aria-label={`${definition.name} size`} className="dash-custom-size" value={sizes[id] || "standard"} onChange={e => resize(id, e.target.value)}><option value="standard">Standard</option><option value="wide">Full width</option></select><div className="dash-custom-order"><button type="button" disabled={index === 0} aria-label={`Move ${definition.name} up`} onClick={() => reorder(id, enabled[index - 1])}><ArrowUp size={12} /></button><button type="button" disabled={index === enabled.length - 1} aria-label={`Move ${definition.name} down`} onClick={() => { const next = [...enabled]; [next[index], next[index + 1]] = [next[index + 1], next[index]]; updateWidgets(next); }}><ArrowDown size={12} /></button></div></>}</div>; })}</div><div className="dash-dialog-footer"><button type="button" className="dash-button" onClick={() => { updateWidgets(DEFAULT_WIDGETS); setSizes({}); try { localStorage.removeItem("itsss-dashboard-sizes"); } catch { /* Layout resets for this visit. */ } }}>Reset layout</button><span className="dash-dialog-hint">Your layout is saved automatically.</span><button type="button" className="dash-button dash-button-primary" onClick={() => setCustomize(false)}><Check size={13} />Done</button></div></div></div>}
  </div>;
}
