export type ERPRecord = { id: string; [key: string]: any };
export type Store = Record<string, ERPRecord[]>;
export type Field = { key: string; label: string; type: string; required?: boolean; options?: string[]; relation?: string; section?: string; formula?: string; allowCustom?: boolean; dictionary?: string };
export type Module = { id: string; name: string; singular: string; group: string; icon: string; description: string; fields: Field[]; columns: string[]; statuses?: string[] };

const f = (key: string, label: string, type = 'text', extra: Partial<Field> = {}): Field => ({ key, label, type, ...extra });
const required = (key: string, label: string, type = 'text') => f(key, label, type, { required: true });
const select = (key: string, label: string, options: string[], requiredValue = false) => f(key, label, 'select', { options, required: requiredValue });
const rel = (key: string, label: string, relation: string, requiredValue = false) => f(key, label, 'relation', { relation, required: requiredValue });
const note = f('notes', 'Notes', 'textarea');
const attachments = f('attachments', 'Attachments', 'file');
const priority = select('priority', 'Priority', ['Low', 'Normal', 'High', 'Critical']);
const city = f('city', 'City');
const money = (key: string, label: string, requiredValue = false) => f(key, label, 'currency', { required: requiredValue });
const date = (key: string, label: string, requiredValue = false) => f(key, label, 'date', { required: requiredValue });
const status = (values: string[]) => select('status', 'Status', values);
const customer = rel('customer', 'Lead / company', 'customers');
const site = rel('site', 'Site', 'sites');
const project = rel('project', 'Project', 'projects');
const employee = rel('employee', 'Employee', 'employees');
const technician = rel('technician', 'Technician', 'employees');
const supplier = rel('supplier', 'Supplier', 'suppliers');
const product = rel('product', 'Product', 'products');
const methods = ['Cash', 'UPI', 'Bank Transfer', 'Cheque', 'Credit Card', 'Debit Card', 'Other'];
const sourceOptions = ['Google Ads', 'Meta Ads', 'Instagram', 'Facebook', 'Website', 'WhatsApp', 'Phone Call', 'Google Business Profile', 'Referral', 'Existing Customer', 'Walk-in', 'Justdial', 'IndiaMART', 'Salesperson', 'Partner', 'Offline Advertisement', 'Other'];
const leadStatuses = ['New', 'Contacted', 'Interested', 'Requirement Gathering', 'Site Survey Required', 'Site Survey Completed', 'Negotiation', 'Follow-up', 'Won', 'Lost', 'On Hold', 'Not Interested', 'Invalid Lead'];
const projectStatuses = ['Planning', 'Material Procurement', 'Material Ready', 'Installation Scheduled', 'Installation In Progress', 'Testing', 'Customer Approval', 'Completed', 'On Hold', 'Cancelled'];
const expenseCategories = ['Product Purchase', 'Labour', 'Technician', 'Petrol', 'Diesel', 'Travel', 'Food', 'Hotel', 'Courier', 'Electricity', 'Internet', 'Rent', 'Advertising', 'Software', 'Subscription', 'Salary', 'Repair', 'Office Supplies', 'Miscellaneous'];
const renewalStatuses = ['Active', 'Due Soon', 'Renewed', 'Expired', 'Cancelled'];
const approval = select('approvalStatus', 'Approval', ['Pending', 'Approved', 'Rejected']);
const definition = (id: string, name: string, singular: string, group: string, icon: string, description: string, fields: Field[], columns: string[], statuses?: string[]): Module => ({ id, name, singular, group, icon, description, fields, columns, statuses });

export const modules: Module[] = [
  definition('leads', 'Leads', 'Lead', 'CRM', 'Users', 'Manage company profiles, contacts, addresses and sales progress in one place.', [required('name', 'Company / lead name'), f('company', 'Legacy company name'), f('contactPerson', 'Contact person'), f('contactDesignation', 'Contact designation'), f('additionalContacts', 'Other contact people and details', 'textarea'), f('mobile', 'Contact phone', 'tel'), f('alternateMobile', 'Alternate mobile', 'tel'), f('whatsapp', 'WhatsApp', 'tel'), f('email', 'Email', 'email'), f('website', 'Website', 'url'), f('address', 'Company address', 'textarea'), f('billingAddress', 'Billing address', 'textarea'), f('installationAddress', 'Installation address', 'textarea'), f('siteAddresses', 'Other site addresses', 'textarea'), city, f('state', 'State'), f('pinCode', 'PIN code'), f('gstNumber', 'GST number'), f('pan', 'PAN'), f('otherEmails', 'Other contact emails', 'textarea'), f('paymentTerms', 'Payment terms'), money('creditLimit', 'Credit limit'), select('category', 'Company category', ['Individual', 'SME', 'Corporate', 'School', 'College', 'Hospital', 'Hotel', 'Restaurant', 'Factory', 'Government', 'Retail Shop', 'Residential Society', 'NGO', 'Dealer', 'Distributor']), select('type', 'Lead type', ['Product', 'Service', 'Product & Service', 'AMC', 'Renewal']), rel('product', 'Required product', 'products'), rel('service', 'Required service', 'services'), f('requirement', 'Estimated requirement', 'textarea'), money('budget', 'Estimated budget'), select('source', 'Lead source', sourceOptions), rel('assignedTo', 'Assigned employee', 'employees'), priority, status(leadStatuses), date('expectedClosing', 'Expected closing date'), date('lastContact', 'Last contact date'), date('nextFollowup', 'Next follow-up date'), customer, project, note, attachments], ['name', 'contactPerson', 'mobile', 'city', 'assignedTo', 'status', 'nextFollowup'], leadStatuses),
  definition('followups', 'Follow-ups', 'Follow-up', 'CRM', 'Phone', 'Calls, meetings, visits and reminders with a complete contact history.', [required('name', 'Activity title'), rel('lead', 'Lead', 'leads'), customer, project, select('type', 'Activity type', ['Phone Call', 'WhatsApp', 'Email', 'Meeting', 'Site Visit', 'Video Call', 'Note']), rel('assignedTo', 'Assigned employee', 'employees'), f('dueAt', 'Due date & time', 'datetime-local', { required: true }), priority, status(['Scheduled', 'Completed', 'Missed', 'Cancelled']), f('comments', 'Comments', 'textarea'), f('outcome', 'Outcome', 'textarea'), date('nextFollowup', 'Next follow-up'), note], ['name', 'lead', 'type', 'assignedTo', 'dueAt', 'status'], ['Scheduled', 'Completed', 'Missed', 'Cancelled']),
  definition('customers', 'Customers', 'Customer', 'CRM', 'Building2', 'A unified view of contacts, sites, projects, installed assets and lifetime value.', [required('name', 'Customer name'), f('company', 'Company name'), f('billingAddress', 'Billing address', 'textarea'), f('installationAddress', 'Installation address', 'textarea'), f('siteAddresses', 'Additional site addresses', 'textarea'), f('contactPersons', 'Contact persons', 'textarea'), f('mobile', 'Mobile', 'tel'), f('alternateMobile', 'Other phone', 'tel'), f('email', 'Email', 'email'), f('otherEmails', 'Other emails', 'textarea'), city, f('state', 'State'), f('gstNumber', 'GST number'), f('pan', 'PAN'), select('category', 'Customer category', ['Individual', 'SME', 'Corporate', 'School', 'College', 'Hospital', 'Hotel', 'Restaurant', 'Factory', 'Government', 'Retail Shop', 'Residential Society', 'NGO', 'Dealer', 'Distributor']), date('customerSince', 'Customer since'), money('creditLimit', 'Credit limit'), f('paymentTerms', 'Payment terms'), status(['Active', 'Inactive']), note, attachments], ['name', 'company', 'city', 'category', 'mobile', 'status'], ['Active', 'Inactive']),
  definition('contacts', 'Contacts', 'Contact', 'CRM', 'Contact', 'Keep billing, technical and site contacts connected to their customers.', [required('name', 'Contact name'), customer, site, f('designation', 'Designation'), f('department', 'Department'), f('mobile', 'Mobile', 'tel'), f('whatsapp', 'WhatsApp', 'tel'), f('email', 'Email', 'email'), date('birthday', 'Birthday'), select('type', 'Contact type', ['Primary', 'Site', 'Billing', 'Technical', 'Other']), f('primary', 'Primary contact', 'checkbox'), note], ['name', 'customer', 'designation', 'type', 'mobile', 'email']),
  definition('opportunities', 'Opportunities', 'Opportunity', 'CRM', 'Target', 'Track additional sales and renewals for existing customers.', [required('name', 'Opportunity name'), customer, rel('lead', 'Lead', 'leads'), rel('service', 'Service', 'services'), money('value', 'Expected value'), f('probability', 'Probability %', 'number'), rel('assignedTo', 'Owner', 'employees'), date('closingDate', 'Expected closing'), status(['Open', 'Negotiation', 'Won', 'Lost']), note], ['name', 'customer', 'value', 'probability', 'closingDate', 'status'], ['Open', 'Negotiation', 'Won', 'Lost']),
  definition('projects', 'Projects', 'Project', 'Projects', 'FolderKanban', 'Connect customer delivery, procurement, installation, payments and profitability.', [required('name', 'Project name'), customer, site, rel('lead', 'Source lead', 'leads'), rel('manager', 'Project manager', 'employees'), rel('salesperson', 'Salesperson', 'employees'), f('technicians', 'Assigned technicians', 'multiselect', { relation: 'employees' }), date('startDate', 'Start date'), date('dueDate', 'Expected completion'), date('completedDate', 'Actual completion'), money('value', 'Project value', true), money('estimatedCost', 'Estimated cost'), f('actualCost', 'Actual cost', 'formula'), f('profit', 'Profit', 'formula'), f('margin', 'Profit margin %', 'formula'), f('progress', 'Progress %', 'number'), priority, rel('service', 'Service', 'services'), f('type', 'Project type'), f('department', 'Department'), city, status(projectStatuses), date('paymentDueDate', 'Payment due date'), note, attachments], ['name', 'customer', 'city', 'progress', 'status', 'value', 'dueDate'], projectStatuses),
  definition('projectPosts', 'Project Timeline', 'Project Post', 'Projects', 'MessagesSquare', 'Progress updates, comments and installation photos or videos within each project.', [rel('project', 'Project', 'projects', true), select('kind', 'Post type', ['Update', 'Comment'], true), f('body', 'Details / comment', 'textarea'), f('media', 'Photos, videos and audio', 'file'), rel('parent', 'Reply to', 'projectPosts'), f('progress', 'Progress %', 'number'), select('stage', 'Project stage', projectStatuses), f('pinned', 'Pinned', 'checkbox'), f('authorId', 'Author ID', 'formula'), f('authorName', 'Author', 'formula'), f('authorRole', 'Author role', 'formula'), f('postedAt', 'Posted at', 'formula')], ['body', 'project', 'kind', 'authorName', 'postedAt']),
  definition('tasks', 'Project Tasks', 'Task', 'Projects', 'ListChecks', 'Dependencies, checklists, subtasks and time tracking for every project.', [required('name', 'Task name'), project, f('description', 'Description', 'textarea'), rel('assignedTo', 'Assigned employee', 'employees'), date('dueDate', 'Due date'), priority, status(['To Do', 'In Progress', 'Blocked', 'Completed']), f('estimatedHours', 'Estimated hours', 'number'), f('actualHours', 'Actual hours', 'number'), rel('dependsOn', 'Task dependency', 'tasks'), rel('parentTask', 'Parent task', 'tasks'), f('checklist', 'Checklist (one item per line)', 'textarea'), f('progress', 'Progress %', 'number'), date('startDate', 'Start date'), date('completedDate', 'Completion date'), f('comments', 'Comments', 'textarea'), note, attachments], ['name', 'project', 'assignedTo', 'priority', 'dueDate', 'progress', 'status'], ['To Do', 'In Progress', 'Blocked', 'Completed']),
  definition('sites', 'Sites', 'Site', 'Projects', 'MapPin', 'Customer locations, access instructions, diagrams and assigned teams.', [required('name', 'Site name'), rel('customer', 'Customer', 'customers', true), f('address', 'Full address', 'textarea'), f('locationUrl', 'GPS / navigation link', 'url'), city, f('state', 'State'), rel('contact', 'Contact person', 'contacts'), f('phone', 'Site phone', 'tel'), f('email', 'Site email', 'email'), f('workingHours', 'Working hours'), f('accessInstructions', 'Access instructions', 'textarea'), technician, rel('manager', 'Project manager', 'employees'), select('category', 'Category', ['Office', 'Retail', 'Hospital', 'Factory', 'Residential', 'School', 'Other']), status(['Active', 'Installation', 'Maintenance', 'Inactive']), f('photos', 'Site photos', 'file'), f('networkDiagram', 'Network diagram', 'file'), f('cctvDiagram', 'CCTV diagram', 'file'), rel('credentialRef', 'Credential reference', 'vault'), note], ['name', 'customer', 'city', 'technician', 'status'], ['Active', 'Installation', 'Maintenance', 'Inactive']),
  definition('surveys', 'Site Surveys', 'Survey', 'Projects', 'ClipboardList', 'Capture complete installation requirements and technical evidence on site.', [required('name', 'Survey name'), customer, site, rel('lead', 'Lead', 'leads'), date('surveyDate', 'Survey date', true), technician, f('requirement', 'Requirement', 'textarea'), f('floors', 'Number of floors', 'number'), f('rooms', 'Number of rooms', 'number'), f('existingNetwork', 'Existing network', 'textarea'), f('existingCctv', 'Existing CCTV', 'textarea'), f('existingInternet', 'Existing internet'), f('existingRack', 'Existing rack'), f('existingCabling', 'Existing cabling'), f('power', 'Power availability'), f('ups', 'UPS availability'), f('challenges', 'Installation challenges', 'textarea'), f('cableLength', 'Required cable length (m)', 'number'), f('devices', 'Required devices', 'textarea'), f('labour', 'Labour requirement', 'textarea'), f('estimatedHours', 'Estimated installation hours', 'number'), status(['Scheduled', 'In Progress', 'Completed', 'Cancelled']), f('photos', 'Photos', 'file'), f('videos', 'Videos', 'file'), f('floorPlans', 'Floor plans', 'file'), f('networkDiagrams', 'Network diagrams', 'file'), f('cctvPlacements', 'CCTV placement images', 'file'), attachments, note], ['name', 'customer', 'site', 'surveyDate', 'technician', 'status'], ['Scheduled', 'In Progress', 'Completed', 'Cancelled']),
  definition('workOrders', 'Work Orders', 'Work Order', 'Projects', 'ClipboardCheck', 'Schedule jobs and produce service reports with completion evidence.', [required('name', 'Work order number'), customer, site, project, technician, f('description', 'Job description', 'textarea'), f('products', 'Required products', 'multiselect', { relation: 'products' }), f('services', 'Services', 'multiselect', { relation: 'services' }), f('tools', 'Tools required', 'textarea'), f('spareParts', 'Spare parts', 'textarea'), f('estimatedHours', 'Estimated hours', 'number'), f('scheduledAt', 'Scheduled date & time', 'datetime-local'), priority, status(['Scheduled', 'Assigned', 'In Progress', 'Completed', 'Revisit Required', 'Cancelled']), f('technicianNotes', 'Technician notes', 'textarea'), f('customerComments', 'Customer comments', 'textarea'), f('signature', 'Customer signature', 'file'), date('completedDate', 'Completion date'), f('photos', 'Completion photos', 'file'), f('actualHours', 'Time spent (hours)', 'number'), f('materialUsed', 'Material used', 'textarea'), f('report', 'Service report', 'file')], ['name', 'customer', 'project', 'technician', 'scheduledAt', 'status'], ['Scheduled', 'Assigned', 'In Progress', 'Completed', 'Revisit Required', 'Cancelled']),
  definition('technicianJobs', 'Technician Jobs', 'Job', 'Projects', 'HardHat', 'Mobile job updates, site navigation, material usage and completion proof.', [required('name', 'Job name'), rel('workOrder', 'Work order', 'workOrders'), project, customer, site, technician, f('scheduledAt', 'Scheduled date & time', 'datetime-local'), f('instructions', 'Job instructions', 'textarea'), f('equipment', 'Required equipment', 'textarea'), rel('allocation', 'Assigned material', 'allocations'), f('navigationUrl', 'Navigation link', 'url'), status(['Assigned', 'Reached Site', 'Work Started', 'Work Paused', 'Work Completed', 'Unable to Complete', 'Revisit Required']), f('beforePhotos', 'Before photos', 'file'), f('installationPhotos', 'Installation photos', 'file'), f('afterPhotos', 'After photos', 'file'), f('serialNumbers', 'Serial numbers', 'textarea'), f('signature', 'Customer signature', 'file'), f('materialUsed', 'Material used', 'textarea'), f('completionProof', 'Completion proof', 'file'), note], ['name', 'technician', 'site', 'scheduledAt', 'status'], ['Assigned', 'Reached Site', 'Work Started', 'Work Paused', 'Work Completed', 'Unable to Complete', 'Revisit Required']),
  definition('products', 'Products', 'Product', 'Products', 'Package', 'Your complete catalogue of CCTV, networking, hardware and software products.', [required('sku', 'SKU'), required('name', 'Product name'), select('category', 'Category', ['CCTV', 'Networking', 'IT Hardware', 'Software', 'Other']), f('subcategory', 'Subcategory'), f('brand', 'Brand'), f('model', 'Model'), f('description', 'Description', 'textarea'), f('hsn', 'HSN code'), f('gstRate', 'GST %', 'number'), money('purchasePrice', 'Purchase price'), money('sellingPrice', 'Selling price'), money('mrp', 'MRP'), money('dealerPrice', 'Dealer price'), money('installationCharges', 'Installation charges'), f('minimumStock', 'Minimum stock', 'number'), f('warrantyMonths', 'Warranty (months)', 'number'), supplier, f('serialTracking', 'Serial number tracking', 'checkbox'), status(['Active', 'Inactive']), attachments], ['sku', 'name', 'category', 'brand', 'sellingPrice', 'minimumStock', 'status'], ['Active', 'Inactive']),
  definition('services', 'Services', 'Service', 'Services', 'Wrench', 'Price installation, support, software and digital services consistently.', [required('name', 'Service name'), select('category', 'Category', ['CCTV', 'Networking', 'IT Support', 'Website Development', 'Social Media', 'Digital Marketing', 'Software Licensing', 'Hosting', 'Other']), money('standardPrice', 'Standard price'), money('hourlyPrice', 'Hourly price'), money('dailyPrice', 'Daily price'), money('installationPrice', 'Installation price'), money('amcPrice', 'AMC price'), f('gstRate', 'GST %', 'number'), f('estimatedHours', 'Estimated hours', 'number'), f('description', 'Description', 'textarea'), status(['Active', 'Inactive'])], ['name', 'category', 'standardPrice', 'estimatedHours', 'status'], ['Active', 'Inactive']),
  definition('assets', 'Installed Assets', 'Asset', 'Products', 'ScanLine', 'Trace installed devices from purchase through warranty and service history.', [required('name', 'Asset name'), customer, site, project, product, f('brand', 'Brand'), f('model', 'Model'), required('serialNumber', 'Serial number'), f('macAddress', 'MAC address'), f('ipAddress', 'IP address'), date('installationDate', 'Installation date'), date('warrantyExpiry', 'Warranty expiry'), supplier, date('purchaseDate', 'Purchase date'), money('purchasePrice', 'Purchase price'), money('sellingPrice', 'Selling price'), status(['Active', 'Under Repair', 'Replaced', 'Retired']), f('serviceHistory', 'Service history', 'textarea'), note], ['name', 'customer', 'site', 'serialNumber', 'warrantyExpiry', 'status'], ['Active', 'Under Repair', 'Replaced', 'Retired']),
  definition('networks', 'Network Records', 'Network Record', 'Services', 'Network', 'Device configuration, IP addressing, racks and topology references.', [required('name', 'Device name'), customer, site, rel('asset', 'Installed asset', 'assets'), select('type', 'Device type', ['Router', 'Switch', 'Firewall', 'Access Point', 'Server', 'Rack', 'Patch Panel']), f('ipAddress', 'IP address'), f('vlans', 'VLANs', 'textarea'), f('isp', 'ISP details'), f('wanIp', 'WAN IP'), f('lanRange', 'LAN range'), f('rack', 'Rack details'), f('patchPanel', 'Patch panel details'), f('topology', 'Topology diagram', 'file'), rel('credentialRef', 'Credentials reference', 'vault'), f('firmware', 'Firmware version'), f('configuration', 'Configuration notes', 'textarea'), status(['Active', 'Maintenance', 'Offline']), note], ['name', 'site', 'type', 'ipAddress', 'firmware', 'status'], ['Active', 'Maintenance', 'Offline']),
  definition('cctv', 'CCTV Records', 'Camera Record', 'Services', 'Camera', 'Camera placement, recorder channels and recording retention.', [required('name', 'Camera name'), customer, site, f('location', 'Camera location'), f('cameraNumber', 'Camera number'), f('ipAddress', 'Camera IP'), select('type', 'Camera type', ['IP Camera', 'Analog Camera', 'PTZ Camera', 'Wi-Fi Camera']), rel('recorder', 'DVR / NVR', 'assets'), f('channel', 'Channel number', 'number'), f('hdd', 'HDD capacity'), f('recordingDays', 'Recording days', 'number'), date('installationDate', 'Installation date'), date('warrantyExpiry', 'Warranty expiry'), f('serialNumber', 'Serial number'), status(['Active', 'Offline', 'Under Repair', 'Retired']), f('serviceHistory', 'Service history', 'textarea'), f('layout', 'CCTV layout diagram', 'file'), note], ['name', 'site', 'location', 'ipAddress', 'channel', 'status'], ['Active', 'Offline', 'Under Repair', 'Retired']),
  definition('websites', 'Website Projects', 'Website Project', 'Services', 'Globe', 'Move websites from requirements to launch and maintenance.', [required('name', 'Website name'), project, customer, f('domain', 'Domain'), rel('hosting', 'Hosting', 'hosting'), select('cms', 'CMS', ['WordPress', 'Custom', 'Shopify', 'Webflow', 'Other']), rel('loginRef', 'WordPress login reference', 'vault'), f('hostingProvider', 'Hosting provider'), f('domainProvider', 'Domain provider'), date('sslExpiry', 'SSL expiry'), f('theme', 'Theme'), f('plugins', 'Plugins', 'textarea'), rel('developer', 'Developer', 'employees'), rel('clientContact', 'Client contact', 'contacts'), status(['Requirement', 'Sitemap', 'Design', 'Content', 'Development', 'Testing', 'Client Review', 'Revision', 'Launch', 'Maintenance']), f('pages', 'Pages', 'textarea'), f('features', 'Features', 'textarea'), f('contentStatus', 'Content status'), f('approvals', 'Client approvals', 'textarea'), f('revisions', 'Revision requests', 'textarea'), date('launchDate', 'Launch date'), f('maintenanceTasks', 'Maintenance tasks', 'textarea'), note], ['name', 'customer', 'domain', 'developer', 'launchDate', 'status'], ['Requirement', 'Sitemap', 'Design', 'Content', 'Development', 'Testing', 'Client Review', 'Revision', 'Launch', 'Maintenance']),
  definition('socialAccounts', 'Social Accounts', 'Social Account', 'Marketing', 'Megaphone', 'Manage client profiles, posting cadence and retainers.', [required('name', 'Account name'), customer, select('platform', 'Platform', ['Facebook', 'Instagram', 'LinkedIn', 'YouTube', 'Other']), f('profileUrl', 'Profile link', 'url'), f('postingFrequency', 'Posting frequency'), money('monthlyPackage', 'Monthly package'), rel('assignedTo', 'Assigned team member', 'employees'), status(['Active', 'Paused', 'Inactive']), note], ['name', 'customer', 'platform', 'monthlyPackage', 'assignedTo', 'status'], ['Active', 'Paused', 'Inactive']),
  definition('content', 'Content Calendar', 'Content Item', 'Marketing', 'Image', 'Plan, approve, schedule and track published social content.', [required('name', 'Post title'), customer, rel('account', 'Social account', 'socialAccounts'), date('postDate', 'Post date'), select('type', 'Post type', ['Image', 'Carousel', 'Reel', 'Video', 'Story', 'Article']), f('caption', 'Caption', 'textarea'), f('creative', 'Creative', 'file'), status(['Idea', 'Designing', 'Client Approval', 'Approved', 'Scheduled', 'Published']), f('clientApproval', 'Client approval', 'checkbox'), f('publishedUrl', 'Published link', 'url'), f('scheduledAt', 'Scheduled date & time', 'datetime-local'), rel('campaign', 'Campaign', 'campaigns'), rel('assignedTo', 'Assigned member', 'employees'), note], ['name', 'customer', 'account', 'postDate', 'type', 'status'], ['Idea', 'Designing', 'Client Approval', 'Approved', 'Scheduled', 'Published']),
  definition('campaigns', 'Ad Campaigns', 'Campaign', 'Marketing', 'MousePointerClick', 'Measure budget, spend, leads, conversions and advertising returns.', [required('name', 'Campaign name'), customer, select('platform', 'Platform', ['Meta Ads', 'Google Ads', 'LinkedIn Ads', 'YouTube', 'Other']), f('objective', 'Objective'), date('startDate', 'Start date'), date('endDate', 'End date'), money('budget', 'Budget'), money('dailyBudget', 'Daily budget'), f('targetLocation', 'Target location'), f('audience', 'Audience', 'textarea'), f('creative', 'Creative', 'file'), f('landingPage', 'Landing page', 'url'), money('spend', 'Spend'), f('impressions', 'Impressions', 'number'), f('reach', 'Reach', 'number'), f('clicks', 'Clicks', 'number'), f('leadCount', 'Leads', 'number'), f('conversions', 'Conversions', 'number'), money('conversionRevenue', 'Conversion revenue'), f('cpc', 'Cost per click', 'formula'), f('cpl', 'Cost per lead', 'formula'), f('conversionRate', 'Conversion rate %', 'formula'), f('roas', 'ROAS', 'formula'), status(['Draft', 'Active', 'Paused', 'Completed']), note], ['name', 'customer', 'platform', 'budget', 'spend', 'leadCount', 'status'], ['Draft', 'Active', 'Paused', 'Completed']),
  definition('suppliers', 'Suppliers', 'Supplier', 'Purchases', 'Truck', 'Vendor contacts, terms and connected purchase/payment history.', [required('name', 'Company name'), f('contactPerson', 'Contact person'), f('mobile', 'Phone', 'tel'), f('email', 'Email', 'email'), f('address', 'Address', 'textarea'), city, f('gstNumber', 'GST number'), f('productsSupplied', 'Products supplied', 'textarea'), f('servicesSupplied', 'Services supplied', 'textarea'), f('paymentTerms', 'Payment terms'), money('creditLimit', 'Credit limit'), status(['Active', 'Inactive']), note], ['name', 'contactPerson', 'city', 'mobile', 'paymentTerms', 'status'], ['Active', 'Inactive']),
  definition('purchaseRequests', 'Purchase Requests', 'Purchase Request', 'Purchases', 'ShoppingCart', 'Raise material requirements for manager approval.', [required('name', 'Request number'), project, product, f('quantity', 'Quantity', 'number', { required: true }), rel('requestedBy', 'Requested by', 'employees'), date('requiredBy', 'Required by'), priority, approval, status(['Requested', 'Approved', 'Ordered', 'Rejected']), note], ['name', 'project', 'product', 'quantity', 'requiredBy', 'status'], ['Requested', 'Approved', 'Ordered', 'Rejected']),
  definition('purchaseOrders', 'Purchase Orders', 'Purchase Order', 'Purchases', 'FileText', 'Purchase authorization, supplier delivery and goods receiving.', [required('name', 'Purchase order number'), rel('supplier', 'Supplier', 'suppliers', true), project, rel('product', 'Product', 'products', true), f('quantity', 'Quantity', 'number', { required: true }), money('rate', 'Rate', true), f('gstRate', 'GST %', 'number'), f('total', 'Total amount', 'formula'), date('orderDate', 'Order date'), date('deliveryDate', 'Delivery date'), f('paymentTerms', 'Payment terms'), f('location', 'Receiving location'), approval, status(['Draft', 'Pending Approval', 'Approved', 'Ordered', 'Partially Received', 'Received', 'Cancelled']), note], ['name', 'supplier', 'product', 'quantity', 'total', 'deliveryDate', 'status'], ['Draft', 'Pending Approval', 'Approved', 'Ordered', 'Partially Received', 'Received', 'Cancelled']),
  definition('purchases', 'Goods Received', 'Purchase', 'Purchases', 'PackageCheck', 'Post goods receipts into stock exactly once.', [required('name', 'Receipt number'), rel('purchaseOrder', 'Purchase order', 'purchaseOrders'), supplier, rel('product', 'Product', 'products', true), f('quantity', 'Quantity received', 'number', { required: true }), money('rate', 'Purchase rate', true), f('gstRate', 'GST %', 'number'), f('total', 'Total amount', 'formula'), date('date', 'Receipt date', true), required('location', 'Inventory location'), date('dueDate', 'Supplier payment due'), status(['Draft', 'Received', 'Returned']), f('serialNumbers', 'Serial numbers', 'textarea'), note, attachments], ['name', 'supplier', 'product', 'quantity', 'total', 'location', 'status'], ['Draft', 'Received', 'Returned']),
  definition('supplierPayments', 'Supplier Payments', 'Supplier Payment', 'Purchases', 'CreditCard', 'Record partial or full settlements against supplier purchases.', [required('name', 'Payment reference'), rel('supplier', 'Supplier', 'suppliers', true), rel('purchase', 'Purchase', 'purchases'), money('amount', 'Amount', true), date('date', 'Payment date', true), select('method', 'Payment method', methods), status(['Pending', 'Paid', 'Cancelled']), note, attachments], ['name', 'supplier', 'purchase', 'amount', 'date', 'status'], ['Pending', 'Paid', 'Cancelled']),
  definition('inventory', 'Inventory', 'Stock Record', 'Products', 'Boxes', 'Location stock with available, reserved, damaged and returned quantities.', [required('name', 'Stock record name'), rel('product', 'Product', 'products', true), required('location', 'Location'), f('quantity', 'Physical stock', 'number', { required: true }), f('reserved', 'Reserved stock', 'number'), f('damaged', 'Damaged stock', 'number'), f('returned', 'Returned stock', 'number'), f('available', 'Available stock', 'formula'), money('unitCost', 'Unit cost'), f('value', 'Inventory value', 'formula'), rel('technician', 'Technician', 'employees'), project, f('adjustmentReason', 'Adjustment reason', 'textarea'), note], ['name', 'product', 'location', 'quantity', 'reserved', 'available', 'value']),
  definition('serials', 'Serial Numbers', 'Serial Record', 'Products', 'Barcode', 'End-to-end serial, IMEI, MAC, key reference and batch traceability.', [required('name', 'Serial / identifier'), product, select('type', 'Identifier type', ['Serial Number', 'IMEI', 'MAC Address', 'License Key Reference', 'Batch Number']), supplier, customer, site, project, rel('asset', 'Installed asset', 'assets'), f('location', 'Current location'), date('purchaseDate', 'Purchase date'), date('installationDate', 'Installation date'), date('warrantyExpiry', 'Warranty expiry'), status(['In Stock', 'Reserved', 'Installed', 'Under Repair', 'Returned']), note], ['name', 'product', 'type', 'customer', 'location', 'status'], ['In Stock', 'Reserved', 'Installed', 'Under Repair', 'Returned']),
  definition('stockTransfers', 'Stock Transfers', 'Stock Transfer', 'Products', 'ArrowLeftRight', 'Move stock between locations with validated quantities and a traceable history.', [required('name', 'Transfer number'), rel('product', 'Product', 'products', true), required('fromLocation', 'From location'), required('toLocation', 'To location'), f('quantity', 'Quantity', 'number', { required: true }), date('date', 'Transfer date', true), rel('assignedTo', 'Assigned user', 'employees'), project, status(['Draft', 'Pending Approval', 'Approved', 'Completed', 'Cancelled']), note], ['name', 'product', 'fromLocation', 'toLocation', 'quantity', 'status'], ['Draft', 'Pending Approval', 'Approved', 'Completed', 'Cancelled']),
  definition('allocations', 'Material Allocation', 'Allocation', 'Products', 'Layers', 'Reserve material, issue it to projects, and record usage, waste and returns.', [required('name', 'Allocation number'), rel('product', 'Product', 'products', true), project, technician, required('location', 'Source location'), f('quantity', 'Reserved quantity', 'number', { required: true }), f('usedQuantity', 'Used quantity', 'number'), f('returnedQuantity', 'Returned quantity', 'number'), f('wastage', 'Wastage quantity', 'number'), f('estimatedQuantity', 'Estimated quantity', 'number'), date('date', 'Allocation date', true), approval, status(['Draft', 'Reserved', 'Issued', 'Used', 'Returned', 'Cancelled']), note], ['name', 'product', 'project', 'technician', 'quantity', 'usedQuantity', 'status'], ['Draft', 'Reserved', 'Issued', 'Used', 'Returned', 'Cancelled']),
  definition('stockHistory', 'Stock History', 'Stock Movement', 'Products', 'History', 'An automatic ledger of stock receipts, adjustments, transfers and allocation.', [required('name', 'Movement reference'), product, f('location', 'Location'), f('quantity', 'Stock delta', 'number'), f('reservedDelta', 'Reserved delta', 'number'), f('type', 'Movement type'), f('sourceModule', 'Source module'), f('sourceId', 'Source record'), f('date', 'Date & time', 'datetime-local'), f('actor', 'User'), note], ['name', 'product', 'location', 'quantity', 'type', 'date']),
  definition('expenses', 'Expenses', 'Expense', 'Finance', 'Receipt', 'Approved spending feeds project costs and company profitability.', [required('name', 'Expense description'), date('date', 'Expense date', true), select('category', 'Category', expenseCategories), money('amount', 'Amount', true), money('gst', 'GST amount'), project, employee, supplier, select('method', 'Payment method', methods), f('receipt', 'Receipt', 'file'), approval, status(['Submitted', 'Approved', 'Rejected', 'Paid']), note], ['name', 'date', 'category', 'project', 'amount', 'approvalStatus'], ['Submitted', 'Approved', 'Rejected', 'Paid']),
  definition('payments', 'Customer Payments', 'Payment', 'Finance', 'IndianRupee', 'Record advances, part payments and balance settlements for customer projects.', [required('name', 'Payment reference'), rel('customer', 'Customer', 'customers', true), project, money('amount', 'Amount received', true), date('date', 'Payment date', true), select('type', 'Payment type', ['Advance', 'Partial', 'Balance', 'Refund']), select('method', 'Payment method', methods), f('transactionId', 'Transaction ID'), status(['Pending', 'Received', 'Cancelled']), date('dueDate', 'Due date'), note, attachments], ['name', 'customer', 'project', 'amount', 'method', 'date', 'status'], ['Pending', 'Received', 'Cancelled']),
  definition('income', 'Other Income', 'Income', 'Finance', 'TrendingUp', 'Record revenue earned outside project contracts.', [required('name', 'Income description'), customer, rel('service', 'Service', 'services'), money('amount', 'Amount', true), date('date', 'Income date', true), select('method', 'Payment method', methods), status(['Pending', 'Received', 'Cancelled']), note], ['name', 'customer', 'amount', 'date', 'status'], ['Pending', 'Received', 'Cancelled']),
  definition('receivables', 'Receivables', 'Receivable', 'Finance', 'Wallet', 'Additional customer balances and collection follow-ups; project balances calculate automatically.', [required('name', 'Balance description'), customer, project, money('amount', 'Amount due', true), money('paid', 'Amount paid'), date('dueDate', 'Payment due date', true), f('balance', 'Balance due', 'formula'), status(['Unpaid', 'Partially Paid', 'Paid', 'Overdue']), f('followupNotes', 'Follow-up notes', 'textarea')], ['name', 'customer', 'project', 'amount', 'balance', 'dueDate', 'status'], ['Unpaid', 'Partially Paid', 'Paid', 'Overdue']),
  definition('payables', 'Payables', 'Payable', 'Finance', 'Landmark', 'Track non-purchase supplier dues and settlement status.', [required('name', 'Payable description'), supplier, money('amount', 'Amount due', true), money('paid', 'Amount paid'), date('dueDate', 'Due date', true), f('balance', 'Balance', 'formula'), status(['Unpaid', 'Partially Paid', 'Paid', 'Overdue']), note], ['name', 'supplier', 'amount', 'balance', 'dueDate', 'status'], ['Unpaid', 'Partially Paid', 'Paid', 'Overdue']),
  definition('amc', 'AMC Contracts', 'AMC Contract', 'Contracts', 'ShieldCheck', 'Preventive maintenance visits, contract history and renewal opportunities.', [required('name', 'Contract name'), customer, site, f('system', 'Product / system'), date('startDate', 'Start date', true), date('endDate', 'End date', true), money('amount', 'AMC amount', true), f('visits', 'Number of visits', 'number'), f('visitsCompleted', 'Visits completed', 'number'), f('visitsRemaining', 'Visits remaining', 'formula'), technician, status(renewalStatuses), f('history', 'Contract history', 'textarea'), note, attachments], ['name', 'customer', 'site', 'amount', 'visitsRemaining', 'endDate', 'status'], renewalStatuses),
  definition('licenses', 'Software Licenses', 'License', 'Contracts', 'KeyRound', 'Track seats, safe key references, expiry dates and renewal reminders.', [required('name', 'License name'), customer, product, select('type', 'License type', ['Windows', 'Microsoft 365', 'Google Workspace', 'Antivirus', 'Tally', 'BUSY', 'Server License', 'Other Software']), rel('keyRef', 'License key reference', 'vault'), f('users', 'Number of users', 'number'), date('startDate', 'Start date'), date('expiryDate', 'Expiry date', true), supplier, money('purchasePrice', 'Purchase price'), money('sellingPrice', 'Selling price'), rel('assignedTo', 'Sales owner', 'employees'), status(renewalStatuses), note], ['name', 'customer', 'type', 'users', 'expiryDate', 'status'], renewalStatuses),
  definition('domains', 'Domains', 'Domain', 'Contracts', 'Globe2', 'Registration, renewal amounts and linked client domain history.', [required('name', 'Domain name'), customer, f('registrar', 'Registrar'), date('registrationDate', 'Registration date'), date('expiryDate', 'Expiry date', true), money('renewalAmount', 'Renewal amount'), rel('hosting', 'Hosting', 'hosting'), status(renewalStatuses), note], ['name', 'customer', 'registrar', 'expiryDate', 'renewalAmount', 'status'], renewalStatuses),
  definition('hosting', 'Hosting', 'Hosting Plan', 'Contracts', 'Server', 'Hosting and SSL expiry reminders for each customer.', [required('name', 'Hosting plan name'), customer, f('provider', 'Hosting provider'), f('plan', 'Plan'), date('startDate', 'Start date'), date('expiryDate', 'Hosting expiry', true), date('sslExpiry', 'SSL expiry'), money('renewalAmount', 'Renewal amount'), rel('credentialRef', 'Hosting login reference', 'vault'), status(renewalStatuses), note], ['name', 'customer', 'provider', 'expiryDate', 'sslExpiry', 'status'], renewalStatuses),
  definition('recurring', 'Recurring Services', 'Recurring Service', 'Contracts', 'Repeat', 'Recurring value, annualized revenue and renewal conversion.', [required('name', 'Recurring service name'), customer, rel('service', 'Service', 'services'), select('cycle', 'Billing cycle', ['Monthly', 'Quarterly', 'Annual']), money('amount', 'Amount per cycle', true), f('mrr', 'Monthly recurring revenue', 'formula'), f('arr', 'Annual recurring revenue', 'formula'), date('startDate', 'Start date'), date('renewalDate', 'Next renewal'), status(['Active', 'Due Soon', 'Renewed', 'Expired', 'Cancelled']), note], ['name', 'customer', 'cycle', 'amount', 'mrr', 'renewalDate', 'status'], renewalStatuses),
  definition('tickets', 'Support Tickets', 'Ticket', 'Support', 'Headset', 'Assign and resolve support issues with priority, due dates and customer evidence.', [required('name', 'Ticket number'), customer, site, required('issue', 'Issue', 'textarea'), select('category', 'Category', ['CCTV', 'Networking', 'Computer', 'Software', 'Website', 'Other']), priority, technician, status(['Open', 'Assigned', 'Working', 'Waiting Customer', 'Resolved', 'Closed']), date('createdDate', 'Created date'), date('dueDate', 'Due date'), f('resolution', 'Resolution', 'textarea'), attachments, note], ['name', 'customer', 'issue', 'priority', 'technician', 'status', 'dueDate'], ['Open', 'Assigned', 'Working', 'Waiting Customer', 'Resolved', 'Closed']),
  definition('remoteSupport', 'Remote Support', 'Support Session', 'Support', 'Monitor', 'Record secure remote support methods, time spent and solutions.', [required('name', 'Session title'), customer, rel('ticket', 'Ticket', 'tickets'), technician, select('method', 'Support method', ['AnyDesk', 'TeamViewer', 'Remote Desktop', 'Phone Support', 'Other']), f('issue', 'Issue', 'textarea'), f('startTime', 'Start time', 'datetime-local'), f('endTime', 'End time', 'datetime-local'), f('hours', 'Time spent (hours)', 'formula'), f('solution', 'Solution', 'textarea'), status(['Scheduled', 'In Progress', 'Completed']), note], ['name', 'customer', 'technician', 'method', 'startTime', 'hours', 'status'], ['Scheduled', 'In Progress', 'Completed']),
  definition('warranties', 'Warranties', 'Warranty', 'Support', 'BadgeCheck', 'Warranty coverage, expiry alerts and claim histories.', [required('name', 'Warranty reference'), product, customer, site, rel('asset', 'Installed asset', 'assets'), f('serialNumber', 'Serial number'), date('startDate', 'Warranty start'), date('endDate', 'Warranty end', true), supplier, select('type', 'Warranty type', ['Manufacturer', 'Supplier', 'Extended', 'ITSSS']), status(['Active', 'Expiring Soon', 'Expired', 'Claimed']), f('claims', 'Claims & history', 'textarea'), note], ['name', 'customer', 'product', 'serialNumber', 'endDate', 'status'], ['Active', 'Expiring Soon', 'Expired', 'Claimed']),
  definition('rma', 'RMA & Replacements', 'RMA', 'Support', 'RefreshCw', 'Trace products from customer return through supplier replacement and handover.', [required('name', 'RMA number'), customer, site, product, f('serialNumber', 'Serial number'), supplier, required('fault', 'Fault description', 'textarea'), date('submissionDate', 'Submission date'), status(['Customer Reported', 'Received by ITSSS', 'Sent to Supplier', 'Replacement Received', 'Returned to Customer', 'Closed']), f('replacementSerial', 'Replacement serial number'), date('returnDate', 'Return date'), note, attachments], ['name', 'customer', 'product', 'serialNumber', 'submissionDate', 'status'], ['Customer Reported', 'Received by ITSSS', 'Sent to Supplier', 'Replacement Received', 'Returned to Customer', 'Closed']),
  definition('employees', 'Employees', 'Employee', 'Employees', 'UserRound', 'People, departments and employment details with linked attendance and payroll.', [required('name', 'Employee name'), f('employeeCode', 'Employee ID'), select('role', 'Role', ['Super Admin', 'Admin', 'Manager', 'Sales', 'Technician', 'Developer', 'Marketing', 'Accounts', 'Inventory', 'Viewer']), f('mobile', 'Phone', 'tel'), f('email', 'Email', 'email'), f('address', 'Address', 'textarea'), date('joiningDate', 'Joining date'), money('salary', 'Monthly salary'), select('department', 'Department', ['Management', 'Sales', 'Technical', 'Web Development', 'Digital Marketing', 'Accounts', 'Support', 'Inventory']), status(['Active', 'On Leave', 'Inactive']), f('emergencyContact', 'Emergency contact'), city, attachments], ['name', 'employeeCode', 'role', 'department', 'mobile', 'status'], ['Active', 'On Leave', 'Inactive']),
  definition('attendance', 'Attendance', 'Attendance Record', 'Employees', 'Clock', 'Daily attendance with check-in, GPS, photos and site duty.', [required('name', 'Attendance reference'), rel('employee', 'Employee', 'employees', true), date('date', 'Date', true), select('status', 'Attendance type', ['Present', 'Absent', 'Half Day', 'Leave', 'Work From Home', 'Site Duty']), f('checkIn', 'Check-in time', 'time'), f('checkOut', 'Check-out time', 'time'), f('hours', 'Working hours', 'formula'), f('locationUrl', 'GPS check-in', 'url'), f('photo', 'Photo attendance', 'file'), site, note], ['name', 'employee', 'date', 'status', 'checkIn', 'checkOut', 'hours'], ['Present', 'Absent', 'Half Day', 'Leave', 'Work From Home', 'Site Duty']),
  definition('payroll', 'Payroll', 'Salary Record', 'Employees', 'Banknote', 'Compute salary with bonuses, incentives, deductions and reimbursements.', [required('name', 'Payroll reference'), rel('employee', 'Employee', 'employees', true), required('month', 'Salary month (YYYY-MM)'), money('salary', 'Base salary', true), money('bonus', 'Bonus'), money('incentives', 'Incentives'), money('deductions', 'Deductions'), money('advances', 'Advances'), money('reimbursements', 'Reimbursements'), f('netSalary', 'Net salary', 'formula'), status(['Pending', 'Approved', 'Paid']), date('paymentDate', 'Payment date'), note], ['name', 'employee', 'month', 'salary', 'netSalary', 'status'], ['Pending', 'Approved', 'Paid']),
  definition('employeeExpenses', 'Employee Expenses', 'Expense Claim', 'Employees', 'WalletCards', 'Employee claims, manager decisions and reimbursement history.', [required('name', 'Claim description'), rel('employee', 'Employee', 'employees', true), project, date('date', 'Date', true), select('category', 'Expense type', ['Petrol', 'Travel', 'Food', 'Hotel', 'Parking', 'Courier', 'Miscellaneous']), money('amount', 'Claim amount', true), f('receipt', 'Receipt', 'file'), rel('reviewer', 'Reviewing manager', 'employees'), status(['Submitted', 'Manager Review', 'Approved', 'Rejected', 'Reimbursed']), date('reimbursedDate', 'Reimbursement date'), f('reviewNotes', 'Review notes', 'textarea'), note], ['name', 'employee', 'category', 'amount', 'date', 'status'], ['Submitted', 'Manager Review', 'Approved', 'Rejected', 'Reimbursed']),
  definition('commissions', 'Sales Commissions', 'Commission', 'Employees', 'Percent', 'Compute project sales commissions and track approval and settlement.', [required('name', 'Commission reference'), rel('salesperson', 'Salesperson', 'employees', true), project, money('revenue', 'Commissionable revenue'), select('type', 'Commission type', ['Percentage', 'Fixed']), f('percentage', 'Commission %', 'number'), money('fixedAmount', 'Fixed commission'), f('amount', 'Commission amount', 'formula'), status(['Pending', 'Approved', 'Paid']), date('date', 'Date'), note], ['name', 'salesperson', 'project', 'revenue', 'amount', 'status'], ['Pending', 'Approved', 'Paid']),
  definition('events', 'Business Calendar', 'Event', 'Workspace', 'CalendarDays', 'Plan team meetings, installation visits, leave and important business dates.', [required('name', 'Event title'), select('type', 'Event type', ['Follow-up', 'Meeting', 'Site Survey', 'Installation', 'Service Visit', 'Project Deadline', 'AMC Renewal', 'License Renewal', 'Domain Renewal', 'Hosting Renewal', 'Payment Due', 'Employee Leave', 'Internal Meeting']), f('startAt', 'Start date & time', 'datetime-local', { required: true }), f('endAt', 'End date & time', 'datetime-local'), f('allDay', 'All day', 'checkbox'), customer, site, project, rel('assignedTo', 'Assigned employee', 'employees'), f('location', 'Location'), status(['Scheduled', 'Completed', 'Cancelled']), note], ['name', 'type', 'startAt', 'assignedTo', 'site', 'status'], ['Scheduled', 'Completed', 'Cancelled']),
  definition('notifications', 'Notifications', 'Notification', 'Workspace', 'Bell', 'Your server-generated in-app inbox. Notifications are private to each recipient and read status is saved across devices.', [required('name', 'Notification title'), required('message', 'Message', 'textarea'), select('type', 'Type', ['New Lead', 'Lead Assigned', 'Follow-up Due', 'Project Deadline', 'Site Visit', 'Payment Due', 'Payment Overdue', 'Payment Received', 'Record Update', 'Low Stock', 'Warranty Expiry', 'AMC Renewal', 'Domain Renewal', 'Hosting Renewal', 'License Renewal', 'New Ticket', 'Task Assignment', 'Task Due', 'Calendar Event', 'Project Update', 'Project Comment', 'Material Shortage', 'Cost Overrun', 'Ticket Overdue', 'SSL Expiry']), rel('recipient', 'Recipient', 'employees'), select('channel', 'Channel', ['In-App', 'Email', 'WhatsApp', 'Push Notification']), f('sourceModule', 'Related module'), f('sourceId', 'Related record'), f('recipientName', 'Recipient name'), date('date', 'Date'), f('read', 'Read', 'checkbox'), status(['Pending', 'Delivered', 'Read', 'Failed', 'Resolved']), note], ['name', 'type', 'recipientName', 'channel', 'date', 'status'], ['Pending', 'Delivered', 'Read', 'Failed', 'Resolved']),
  definition('documents', 'Documents', 'Document', 'Workspace', 'Files', 'Upload categorized files with versions and linked business records.', [required('name', 'Document name'), select('relatedModule', 'Related module', ['customers', 'leads', 'projects', 'sites', 'suppliers', 'employees', 'products', 'tickets', 'amc', 'licenses']), f('relatedId', 'Related record ID'), select('category', 'Category', ['Contract', 'Technical', 'Financial', 'Identity', 'Photos', 'Other']), f('file', 'File', 'file', { required: true }), f('version', 'Version', 'number'), f('versionHistory', 'Version history', 'textarea'), date('uploadDate', 'Upload date'), rel('uploadedBy', 'Uploaded by', 'employees'), note], ['name', 'relatedModule', 'category', 'version', 'uploadDate', 'uploadedBy']),
  definition('notes', 'Notes', 'Note', 'Workspace', 'StickyNote', 'Shared, private, pinned and important notes linked to records.', [required('name', 'Note title'), required('content', 'Content', 'textarea'), select('type', 'Note type', ['Private', 'Team', 'Pinned', 'Important']), f('relatedModule', 'Related module'), f('relatedId', 'Related record ID'), rel('author', 'Author', 'employees'), date('date', 'Date')], ['name', 'type', 'relatedModule', 'author', 'date']),
  definition('activities', 'Activity Timeline', 'Activity', 'Workspace', 'Activity', 'Automatic history of changes, payments, allocations and technician updates.', [required('name', 'Activity'), f('module', 'Module'), f('recordId', 'Record ID'), f('action', 'Action'), f('actor', 'User'), f('date', 'Date & time', 'datetime-local'), f('details', 'Details', 'textarea')], ['name', 'module', 'action', 'actor', 'date']),
  definition('communication', 'Communication History', 'Message', 'Workspace', 'Mail', 'Track email and WhatsApp drafts and external delivery references.', [required('name', 'Subject'), customer, rel('lead', 'Lead', 'leads'), project, rel('ticket', 'Ticket', 'tickets'), select('channel', 'Channel', ['Email', 'WhatsApp']), f('recipient', 'Recipient'), f('message', 'Message', 'textarea'), f('attachments', 'Attachments', 'file'), f('date', 'Date & time', 'datetime-local'), status(['Draft', 'Opened in Client', 'Sent', 'Failed']), note], ['name', 'customer', 'channel', 'recipient', 'date', 'status'], ['Draft', 'Opened in Client', 'Sent', 'Failed']),
  definition('users', 'Users', 'User', 'Settings', 'UserCog', 'Manage user profiles, roles and login access. Open a user to set or change their password.', [required('name', 'User name'), required('email', 'Email', 'email'), employee, customer, rel('technician', 'Technician employee', 'employees'), rel('role', 'Role', 'roles'), status(['Active', 'Inactive', 'Locked']), f('twoFactor', '2FA enabled', 'checkbox'), f('lastLogin', 'Last login', 'datetime-local'), note], ['name', 'email', 'role', 'status', 'lastLogin'], ['Active', 'Inactive', 'Locked']),
  definition('roles', 'Roles & Permissions', 'Role', 'Settings', 'LockKeyhole', 'Configure module access and hidden fields for each role.', [required('name', 'Role name'), f('description', 'Description', 'textarea'), f('permissions', 'Allowed actions', 'multiselect', { options: ['View', 'Add', 'Edit', 'Delete', 'Export', 'Approve', 'Assign', 'Download', 'Share'] }), f('allowedModules', 'Allowed module IDs (comma-separated; * for all)', 'textarea'), f('hiddenFields', 'Hidden fields (module.field, comma-separated)', 'textarea'), status(['Active', 'Inactive'])], ['name', 'description', 'permissions', 'status'], ['Active', 'Inactive']),
  definition('customFields', 'Custom Fields', 'Custom Field', 'Settings', 'TextCursorInput', 'Add fields to standard and custom modules without writing code.', [required('name', 'Field label'), required('moduleId', 'Module ID'), required('key', 'Field key'), select('type', 'Field type', ['text', 'number', 'currency', 'date', 'time', 'select', 'checkbox', 'radio', 'email', 'tel', 'url', 'file', 'image', 'relation', 'formula', 'multiselect', 'textarea']), f('required', 'Required', 'checkbox'), f('options', 'Options (one per line)', 'textarea'), f('relation', 'Related module ID'), f('formula', 'Formula (e.g. quantity * rate)'), f('section', 'Section'), status(['Active', 'Inactive'])], ['name', 'moduleId', 'key', 'type', 'required', 'status'], ['Active', 'Inactive']),
  definition('customModules', 'Custom Modules', 'Custom Module', 'Settings', 'Blocks', 'Create specialized operational modules with custom fields and forms.', [required('name', 'Module name'), required('moduleId', 'Module ID (lowercase letters)'), required('singular', 'Singular record name'), f('group', 'Navigation group'), f('description', 'Description', 'textarea'), f('statuses', 'Statuses (one per line)', 'textarea'), f('permissions', 'Permissions', 'textarea'), status(['Active', 'Inactive'])], ['name', 'moduleId', 'group', 'status'], ['Active', 'Inactive']),
  definition('customStatuses', 'Custom Statuses', 'Custom Status', 'Settings', 'Tags', 'Extend lead, project, task, ticket and contract workflows.', [required('name', 'Status name'), required('moduleId', 'Module ID'), f('color', 'Color (hex)'), f('order', 'Display order', 'number'), f('terminal', 'Final status', 'checkbox'), status(['Active', 'Inactive'])], ['name', 'moduleId', 'color', 'order', 'status'], ['Active', 'Inactive']),
  definition('dropdownOptions', 'Dropdown Options', 'Dropdown Option', 'Settings', 'List', 'Reusable business choices added from forms.', [required('name', 'Option label'), required('moduleId', 'Module ID'), required('fieldKey', 'Field key'), status(['Active', 'Inactive'])], ['name', 'moduleId', 'fieldKey', 'status'], ['Active', 'Inactive']),
  definition('customForms', 'Custom Forms', 'Custom Form', 'Settings', 'ClipboardPen', 'Build survey, requirement, feedback and installation checklist forms.', [required('name', 'Form name'), required('moduleId', 'Target module ID'), f('description', 'Description', 'textarea'), f('fieldKeys', 'Included field keys (comma-separated)', 'textarea'), f('instructions', 'Form instructions', 'textarea'), status(['Draft', 'Published', 'Archived'])], ['name', 'moduleId', 'status'], ['Draft', 'Published', 'Archived']),
  definition('categories', 'Categories & Lists', 'List Item', 'Settings', 'List', 'Manage cities, departments, brands, lead sources and business categories.', [required('name', 'Name'), select('type', 'List type', ['City', 'Department', 'Brand', 'Lead Source', 'Product Category', 'Service Category', 'Customer Category', 'Expense Category', 'Payment Method', 'Location']), f('description', 'Description', 'textarea'), status(['Active', 'Inactive'])], ['name', 'type', 'status'], ['Active', 'Inactive']),
  definition('taxes', 'Taxes', 'Tax Rate', 'Settings', 'Calculator', 'Configure GST rates used in products, services and procurement.', [required('name', 'Tax name'), f('rate', 'Tax rate %', 'number', { required: true }), f('hsn', 'HSN / SAC code'), status(['Active', 'Inactive'])], ['name', 'rate', 'hsn', 'status'], ['Active', 'Inactive']),
  definition('templates', 'Document Templates', 'Template', 'Settings', 'LayoutTemplate', 'Customize print headers, reports, contracts and service documents.', [required('name', 'Template name'), select('type', 'Document type', ['Purchase Order', 'Work Order', 'Job Sheet', 'Service Report', 'Project Report', 'AMC Contract', 'Customer Statement', 'Expense Report', 'Inventory Report']), f('header', 'Header text', 'textarea'), f('body', 'Body / terms', 'textarea'), f('footer', 'Footer text', 'textarea'), status(['Active', 'Inactive'])], ['name', 'type', 'status'], ['Active', 'Inactive']),
  definition('automations', 'Automations', 'Automation Rule', 'Settings', 'Zap', 'Control integrated workflow actions and due-date reminders.', [required('name', 'Rule name'), select('trigger', 'Trigger', ['Lead Won', 'Project Completed', 'AMC Expiring', 'License Expiring', 'Low Stock', 'Payment Overdue', 'Ticket Created', 'Project Due']), select('action', 'Action', ['Create Project', 'Create Follow-up', 'Create Renewal Lead', 'Notify', 'Assign Technician']), f('daysBefore', 'Days before due date', 'number'), rel('assignedTo', 'Assigned employee', 'employees'), f('enabled', 'Enabled', 'checkbox'), note], ['name', 'trigger', 'action', 'daysBefore', 'enabled']),
  definition('settings', 'Company Settings', 'Setting', 'Settings', 'Settings', 'Branding, theme preferences and company details for generated documents.', [required('name', 'Company name'), f('fullName', 'Legal company name'), f('demo', 'Show demo workspace label', 'checkbox'), f('address', 'Address', 'textarea'), f('gstNumber', 'GST number'), f('mobile', 'Phone', 'tel'), f('email', 'Email', 'email'), f('website', 'Website', 'url'), f('logo', 'Logo', 'file'), f('brandColor', 'Brand color'), select('theme', 'Theme', ['Light', 'Dark', 'System']), f('sessionMinutes', 'Session timeout (minutes)', 'number'), f('passwordMinLength', 'Password minimum length', 'number'), f('currency', 'Currency'), f('announcementText', 'Announcement text', 'textarea'), f('announcementEnabled', 'Show announcement', 'checkbox'), f('announcementAnimated', 'Animate announcement', 'checkbox')], ['name', 'email', 'gstNumber', 'theme']),
  definition('savedViews', 'Saved Views', 'Saved View', 'Settings', 'Filter', 'Save and share search filters and column preferences.', [required('name', 'View name'), required('moduleId', 'Module ID'), f('search', 'Search text'), f('filters', 'Filters (JSON)', 'textarea'), f('columns', 'Visible columns (comma-separated)', 'textarea'), f('shared', 'Shared with team', 'checkbox'), employee], ['name', 'moduleId', 'shared', 'employee']),
  definition('vault', 'Credential References', 'Credential Reference', 'Settings', 'Shield', 'Store references to a secure password manager; keep secrets in your organization’s vault.', [required('name', 'Reference name'), customer, site, select('type', 'System type', ['Router', 'Firewall', 'NVR', 'DVR', 'Server', 'Website', 'Hosting', 'Admin Panel', 'License']), required('reference', 'Secure vault reference / URL'), f('username', 'Username'), rel('owner', 'Owner', 'employees'), f('allowedRoles', 'Allowed roles (comma-separated)'), f('lastAccess', 'Last access', 'datetime-local'), note], ['name', 'type', 'customer', 'owner', 'reference']),
  definition('backups', 'Backup History', 'Backup Record', 'Settings', 'DatabaseBackup', 'Track manual snapshots, restore points and connected backup destinations.', [required('name', 'Backup name'), select('type', 'Backup type', ['Manual', 'Daily', 'Database', 'Files', 'Scheduled', 'Offsite']), f('date', 'Date & time', 'datetime-local'), f('destination', 'Destination'), f('size', 'Size (bytes)', 'number'), f('file', 'Backup file', 'file'), status(['Completed', 'Restored', 'Failed']), note], ['name', 'type', 'date', 'destination', 'status'], ['Completed', 'Restored', 'Failed']),
  definition('auditLogs', 'Audit Logs', 'Audit Entry', 'Settings', 'ShieldAlert', 'Immutable-style history of mutations, approvals and record restoration.', [required('name', 'Audit event'), f('actor', 'User'), f('action', 'Action'), f('module', 'Module'), f('recordId', 'Record ID'), f('date', 'Date & time', 'datetime-local'), f('device', 'Device'), f('ip', 'IP address'), f('oldValue', 'Old value', 'textarea'), f('newValue', 'New value', 'textarea')], ['name', 'actor', 'action', 'module', 'date'])
];

export const moduleById: Record<string, Module> = Object.fromEntries(modules.map(module => [module.id, module]));

export type DropdownConfig = { kind: 'relation' | 'dictionary' | 'status' | 'option'; targetModule?: string; dictionary?: string };
const dictionaries: Record<string, string> = { 'leads.source': 'Lead Source', 'customers.category': 'Customer Category', 'products.category': 'Product Category', 'services.category': 'Service Category', 'employees.department': 'Department', 'projects.department': 'Department', 'expenses.category': 'Expense Category', 'employeeExpenses.category': 'Expense Category', 'payments.method': 'Payment Method', 'supplierPayments.method': 'Payment Method', 'expenses.method': 'Payment Method', 'income.method': 'Payment Method', 'products.brand': 'Brand', 'assets.brand': 'Brand', 'inventory.location': 'Location', 'purchases.location': 'Location', 'purchaseOrders.location': 'Location', 'allocations.location': 'Location', 'serials.location': 'Location', 'stockTransfers.fromLocation': 'Location', 'stockTransfers.toLocation': 'Location' };
const fixedBusinessFields = new Set(['employees.role', 'recurring.cycle', 'commissions.type', 'payments.type', 'serials.type', 'notes.type', 'documents.relatedModule', 'communication.channel', 'communication.status']);
const fixedWorkflowModules = new Set(['payments', 'supplierPayments', 'income', 'expenses', 'receivables', 'payables', 'payroll', 'employeeExpenses', 'commissions', 'purchases', 'stockTransfers', 'allocations', 'attendance']);

/** Safe list classifications may grow; executable and financial-effect enums stay fixed. */
export function getDropdownConfig(moduleId: string, field: Field): DropdownConfig | undefined {
  if (field.type === 'formula' || ['auditLogs', 'activities', 'stockHistory', 'projectPosts'].includes(moduleId)) return;
  if (field.relation) return { kind: 'relation', targetModule: field.relation };
  if (moduleById[moduleId]?.group === 'Settings' || moduleId === 'notifications' || field.key === 'approvalStatus' || fixedBusinessFields.has(`${moduleId}.${field.key}`)) return;
  const dictionary = field.key === 'city' ? 'City' : dictionaries[`${moduleId}.${field.key}`];
  if (dictionary) return { kind: 'dictionary', dictionary };
  if (!['select', 'radio', 'multiselect'].includes(field.type)) return;
  if (field.key === 'status') return fixedWorkflowModules.has(moduleId) ? undefined : { kind: 'status' };
  return { kind: 'option' };
}

const activeConfig = (rows: ERPRecord[] = []) => rows.filter(row => !row.deletedAt && !row.archivedAt && row.status !== 'Inactive');
function uniqueOptions(options: unknown[]): string[] {
  const seen = new Set<string>();
  return options.map(String).map(value => value.trim()).filter(value => { const key = value.normalize('NFKC').toLocaleLowerCase('en-IN'); if (!value || seen.has(key)) return false; seen.add(key); return true; });
}
function dictionaryDefaults(dictionary?: string): string[] {
  if (dictionary === 'City') return ['Ambala', 'Chandigarh', 'Panchkula', 'Mohali', 'Other Cities'];
  if (dictionary === 'Location') return ['Main Office', 'Shop', 'Warehouse', 'Technician', 'Customer Site'];
  const source: Record<string, [string, string]> = { 'Department': ['employees', 'department'], 'Lead Source': ['leads', 'source'], 'Customer Category': ['customers', 'category'], 'Product Category': ['products', 'category'], 'Service Category': ['services', 'category'], 'Expense Category': ['expenses', 'category'], 'Payment Method': ['payments', 'method'] };
  const [moduleId, key] = source[dictionary || ''] || [];
  return moduleById[moduleId]?.fields.find(field => field.key === key)?.options || [];
}

export function resolveModules(store: Store): Module[] {
  const custom = activeConfig(store.customModules).map(r => definition(r.moduleId, r.name, r.singular || r.name, r.group || 'Custom', 'Blocks', r.description || 'Custom business module.', [required('name', `${r.singular || 'Record'} name`), ...(r.statuses ? [status(String(r.statuses).split('\n').filter(Boolean))] : []), note], ['name', ...(r.statuses ? ['status'] : [])], String(r.statuses || '').split('\n').filter(Boolean)));
  return [...modules, ...custom].map(module => {
    const additions = activeConfig(store.customFields).filter(r => r.moduleId === module.id).map(r => f(r.key, r.name, r.type, { required: !!r.required, options: String(r.options || '').split('\n').filter(Boolean), relation: r.relation || undefined, section: r.section || undefined, formula: r.formula || undefined }));
    const newStatuses = activeConfig(store.customStatuses).filter(r => r.moduleId === module.id).sort((a, b) => Number(a.order || 0) - Number(b.order || 0)).map(r => r.name);
    const fields = module.fields.filter(field => !additions.some(add => add.key === field.key)).concat(additions).map(field => {
      const config = getDropdownConfig(module.id, field);
      const customOptions = config?.dictionary ? activeConfig(store.categories).filter(r => r.type === config.dictionary).map(r => r.name) : [];
      const stored = activeConfig(store.dropdownOptions).filter(r => r.moduleId === module.id && r.fieldKey === field.key).map(r => r.name);
      const customRoles = module.id === 'employees' && field.key === 'role' ? activeConfig(store.roles).map(r => r.name) : [];
      const projectStages = module.id === 'projectPosts' && field.key === 'stage' ? activeConfig(store.customStatuses).filter(r => r.moduleId === 'projects').map(r => r.name) : [];
      const options = uniqueOptions([...(field.options || []), ...dictionaryDefaults(config?.dictionary), ...customOptions, ...customRoles, ...projectStages, ...(config?.kind === 'status' ? newStatuses : []), ...(config || field.key === 'role' && module.id === 'employees' ? stored : [])]);
      const leadSection = field.section || (module.id === 'leads' ? ['name','website','category','gstNumber','pan'].includes(field.key) ? 'Company' : ['contactPerson','contactDesignation','additionalContacts','mobile','alternateMobile','whatsapp','email','otherEmails'].includes(field.key) ? 'Contact details' : ['address','billingAddress','installationAddress','siteAddresses','city','state','pinCode'].includes(field.key) ? 'Addresses' : ['notes','attachments'].includes(field.key) ? 'Notes & files' : 'Sales & follow-up' : field.section);
      return { ...field, section: leadSection, allowCustom: Boolean(config), dictionary: config?.dictionary, options: field.options || options.length ? options : undefined };
    });
    return { ...module, fields, statuses: fields.find(field => field.key === 'status')?.options || module.statuses };
  });
}
