import { modules, type Store, type ERPRecord } from './schema.ts';
import { recalculate } from './engine.ts';

// Illustrative demo records only. The application must label this workspace as demo data.
export function createSeed(): Store {
  const store: Store = Object.fromEntries(modules.map(module => [module.id, []]));
  const put = (moduleId: string, records: ERPRecord[]) => { store[moduleId] = records.map(record => ({ createdAt: '2026-10-01T09:00:00.000Z', updatedAt: '2026-10-06T08:30:00.000Z', demo: true, ...record })); };
  put('employees', [
    { id: 'EMP-001', employeeCode: 'IT-001', name: 'Rohit Sharma', role: 'Super Admin', department: 'Management', mobile: '+91 98760 10001', email: 'rohit@example.com', joiningDate: '2022-04-01', salary: 95000, status: 'Active', city: 'Chandigarh', emergencyContact: 'Family · +91 98760 11001' },
    { id: 'EMP-002', employeeCode: 'IT-002', name: 'Aman Verma', role: 'Sales', department: 'Sales', mobile: '+91 98760 10002', email: 'aman@example.com', joiningDate: '2023-02-15', salary: 45000, status: 'Active', city: 'Ambala' },
    { id: 'EMP-003', employeeCode: 'IT-003', name: 'Simran Kaur', role: 'Manager', department: 'Technical', mobile: '+91 98760 10003', email: 'simran@example.com', joiningDate: '2023-06-01', salary: 62000, status: 'Active', city: 'Chandigarh' },
    { id: 'EMP-004', employeeCode: 'IT-004', name: 'Karan Singh', role: 'Technician', department: 'Technical', mobile: '+91 98760 10004', email: 'karan@example.com', joiningDate: '2024-01-08', salary: 32000, status: 'Active', city: 'Ambala' },
    { id: 'EMP-005', employeeCode: 'IT-005', name: 'Priya Mehta', role: 'Developer', department: 'Web Development', mobile: '+91 98760 10005', email: 'priya@example.com', joiningDate: '2024-05-13', salary: 58000, status: 'Active', city: 'Mohali' },
    { id: 'EMP-006', employeeCode: 'IT-006', name: 'Neha Bansal', role: 'Marketing', department: 'Digital Marketing', mobile: '+91 98760 10006', email: 'neha@example.com', joiningDate: '2024-03-04', salary: 42000, status: 'Active', city: 'Panchkula' },
    { id: 'EMP-007', employeeCode: 'IT-007', name: 'Vikram Sethi', role: 'Accounts', department: 'Accounts', mobile: '+91 98760 10007', email: 'vikram@example.com', joiningDate: '2023-08-01', salary: 48000, status: 'Active', city: 'Chandigarh' },
    { id: 'EMP-008', employeeCode: 'IT-008', name: 'Arjun Patel', role: 'Technician', department: 'Support', mobile: '+91 98760 10008', email: 'arjun@example.com', joiningDate: '2025-01-06', salary: 31000, status: 'Active', city: 'Panchkula' },
    { id: 'EMP-009', employeeCode: 'IT-009', name: 'Ritika Gupta', role: 'Inventory', department: 'Inventory', mobile: '+91 98760 10009', email: 'ritika@example.com', joiningDate: '2025-05-01', salary: 34000, status: 'Active', city: 'Chandigarh' }
  ]);
  const customers = [
    ['CUS-001', 'ABC Retail Store', 'Retail Shop', 'Ambala', 'Aman Verma', 'billing@abcretail.example.com'],
    ['CUS-002', 'Axis Industries', 'Factory', 'Chandigarh', 'Rajiv Sharma', 'it@axisindustries.example.com'],
    ['CUS-003', 'Kaur Hospital', 'Hospital', 'Mohali', 'Dr. Simran Kaur', 'admin@kaurhospital.example.com'],
    ['CUS-004', 'GreenLeaf Hospital', 'Hospital', 'Panchkula', 'Neha Bansal', 'admin@greenleaf.example.com'],
    ['CUS-005', 'Malhotra & Co.', 'SME', 'Mohali', 'Rakesh Malhotra', 'rakesh@malhotra.example.com'],
    ['CUS-006', 'Sethi Industries', 'Corporate', 'Chandigarh', 'Vikram Sethi', 'accounts@sethi.example.com'],
    ['CUS-007', 'Bansal Retail', 'Retail Shop', 'Panchkula', 'Nitin Bansal', 'hello@bansal.example.com'],
    ['CUS-008', 'Sunrise Public School', 'School', 'Ambala', 'Anjali Gupta', 'admin@sunrise.example.com']
  ];
  put('customers', customers.map(([id, name, category, city, contact, email], index) => ({ id, name, company: name, category, city, state: 'Punjab / Haryana', mobile: `+91 98000 2000${index + 1}`, email, contactPersons: contact, billingAddress: `${index + 12}, Business Avenue, ${city}`, installationAddress: `${index + 12}, Business Avenue, ${city}`, customerSince: '2024-02-01', creditLimit: 250000, paymentTerms: '50% advance, balance on handover', status: 'Active', notes: 'Illustrative customer for the demo workspace.' })));
  put('contacts', customers.map(([id, , , , name, email], index) => ({ id: `CON-00${index + 1}`, name, customer: id, designation: index === 2 ? 'Hospital Administrator' : 'IT / Purchase Manager', department: 'Administration', mobile: `+91 98000 2000${index + 1}`, whatsapp: `+91 98000 2000${index + 1}`, email, type: 'Primary', primary: true })));
  put('sites', customers.map(([id, name, category, city], index) => ({ id: `SITE-00${index + 1}`, name: `${name} · Main site`, customer: id, address: `${index + 12}, Business Avenue, ${city}`, city, state: 'Punjab / Haryana', locationUrl: `https://maps.google.com/?q=${encodeURIComponent(city)}`, contact: `CON-00${index + 1}`, phone: `+91 98000 2000${index + 1}`, workingHours: '09:00–18:00, Monday–Saturday', accessInstructions: 'Call the primary contact before arrival. Visitor ID required.', technician: index % 2 ? 'EMP-008' : 'EMP-004', manager: 'EMP-003', category: category === 'Hospital' ? 'Hospital' : category === 'Factory' ? 'Factory' : category === 'School' ? 'School' : 'Office', status: 'Active' })));
  put('suppliers', [
    { id: 'SUP-001', name: 'SecureVision Distributors', contactPerson: 'Deepak Jain', mobile: '+91 98100 30001', email: 'sales@securevision.example.com', address: 'Industrial Area Phase II, Chandigarh', city: 'Chandigarh', productsSupplied: 'IP cameras, NVR, HDD, PoE switches', paymentTerms: '30 days', creditLimit: 500000, status: 'Active' },
    { id: 'SUP-002', name: 'Tricity Network Supplies', contactPerson: 'Sanjay Arora', mobile: '+91 98100 30002', email: 'orders@tricity.example.com', city: 'Mohali', productsSupplied: 'Routers, switches, LAN cable, racks', paymentTerms: '15 days', creditLimit: 350000, status: 'Active' },
    { id: 'SUP-003', name: 'CloudDesk Software', contactPerson: 'Meera Kapoor', mobile: '+91 98100 30003', email: 'licensing@clouddesk.example.com', city: 'Chandigarh', productsSupplied: 'Microsoft 365, antivirus, Windows', paymentTerms: 'Advance', creditLimit: 100000, status: 'Active' }
  ]);
  const products = [
    ['PROD-001', 'CAM-IP-4MP', '4MP IP Dome Camera', 'CCTV', 'IP Camera', 'Hikvision', 'DS-2CD2143', 2450, 3800, 10, 'SUP-001'],
    ['PROD-002', 'NVR-16CH', '16-Channel Network Recorder', 'CCTV', 'NVR', 'Hikvision', 'DS-7616NI', 7800, 11200, 3, 'SUP-001'],
    ['PROD-003', 'RTR-AX1800', 'AX1800 Wi-Fi Router', 'Networking', 'Routers', 'TP-Link', 'Archer AX23', 3100, 4600, 5, 'SUP-002'],
    ['PROD-004', 'SW-POE-8P', '8-Port PoE Switch', 'Networking', 'Switches', 'TP-Link', 'TL-SG1008MP', 4500, 6800, 4, 'SUP-002'],
    ['PROD-005', 'KEY-USB-101', 'USB Keyboard', 'IT Hardware', 'Keyboard', 'Logitech', 'K120', 480, 750, 15, 'SUP-002'],
    ['PROD-006', 'MOUSE-USB', 'Optical USB Mouse', 'IT Hardware', 'Mouse', 'Logitech', 'B100', 240, 450, 15, 'SUP-002'],
    ['PROD-007', 'USB-64GB', '64 GB USB Drive', 'IT Hardware', 'USB Stick', 'SanDisk', 'Ultra Flair', 360, 620, 20, 'SUP-002'],
    ['PROD-008', 'AV-1YR', 'Antivirus · 1 Year', 'Software', 'Antivirus', 'Quick Heal', 'Total Security', 640, 1100, 10, 'SUP-003'],
    ['PROD-009', 'LAN-CAT6', 'CAT6 Cable · 305 m Box', 'Networking', 'LAN Cable', 'D-Link', 'NCB-C6UGRY', 5200, 7800, 3, 'SUP-002'],
    ['PROD-010', 'HDD-SUR-4TB', '4 TB Surveillance HDD', 'CCTV', 'HDD', 'Seagate', 'SkyHawk', 6400, 8900, 4, 'SUP-001']
  ];
  put('products', products.map(([id, sku, name, category, subcategory, brand, model, purchasePrice, sellingPrice, minimumStock, supplier]) => ({ id: String(id), sku, name, category, subcategory, brand, model, purchasePrice, sellingPrice, minimumStock, supplier, gstRate: 18, warrantyMonths: 24, serialTracking: category !== 'Software', status: 'Active', mrp: Number(sellingPrice) * 1.2, installationCharges: category === 'CCTV' ? 500 : 0 })));
  const serviceNames = ['CCTV Installation', 'CCTV Maintenance', 'Networking Installation', 'LAN Cabling', 'Wi-Fi Setup', 'Firewall Configuration', 'Router Configuration', 'Server Setup', 'Computer Repair', 'Laptop Repair', 'Remote IT Support', 'Website Designing', 'Website Development', 'Website Maintenance', 'WordPress Development', 'Hosting', 'Domain Registration', 'Social Media Management', 'Social Media Post Designing', 'Meta Ads Management', 'Google Ads Management', 'SEO', 'Google Workspace Setup', 'Microsoft 365 Setup', 'Email Migration', 'Data Backup', 'Software Installation', 'IT Consultancy'];
  put('services', serviceNames.map((name, index) => ({ id: `SVC-${String(index + 1).padStart(3, '0')}`, name, category: name.includes('CCTV') ? 'CCTV' : ['Networking', 'LAN', 'Wi-Fi', 'Firewall', 'Router', 'Server'].some(s => name.includes(s)) ? 'Networking' : name.includes('Website') || name.includes('WordPress') ? 'Website Development' : name.includes('Social Media') ? 'Social Media' : name.includes('Ads') || name === 'SEO' ? 'Digital Marketing' : name === 'Hosting' || name.includes('Domain') ? 'Hosting' : name.includes('365') || name.includes('Workspace') || name.includes('Software') ? 'Software Licensing' : 'IT Support', standardPrice: [18500, 4500, 32000, 8000, 6500, 12000, 3500, 22000, 1500, 1800, 2500, 18000, 65000, 4500, 35000, 6000, 1400, 18000, 5000, 12000, 14000, 18000][index] || 6500, hourlyPrice: 900, dailyPrice: 6000, installationPrice: 4500, amcPrice: 18000, gstRate: 18, estimatedHours: index === 12 ? 80 : 8, description: `${name} delivered by the ITSSS specialist team.`, status: 'Active' })));
  const projectData = [
    ['PRJ-001', 'CCTV Installation', 'CUS-001', 'SITE-001', 'SVC-001', 'Ambala', 285000, 188000, 80, 'Installation In Progress', '2026-10-15'],
    ['PRJ-002', 'Networking Rollout', 'CUS-002', 'SITE-002', 'SVC-003', 'Chandigarh', 360000, 232000, 62, 'Testing', '2026-10-20'],
    ['PRJ-003', 'Website Development', 'CUS-003', 'SITE-003', 'SVC-013', 'Mohali', 165000, 78000, 42, 'Planning', '2026-10-30'],
    ['PRJ-004', 'Social Media Campaign', 'CUS-004', 'SITE-004', 'SVC-018', 'Panchkula', 108000, 64000, 90, 'Customer Approval', '2026-10-10'],
    ['PRJ-005', 'Office Network Upgrade', 'CUS-005', 'SITE-005', 'SVC-003', 'Mohali', 180000, 115000, 28, 'Material Procurement', '2026-10-05'],
    ['PRJ-006', 'IT Support Retainer', 'CUS-006', 'SITE-006', 'SVC-011', 'Chandigarh', 96000, 46000, 100, 'Completed', '2026-09-25'],
    ['PRJ-007', 'Retail Security Upgrade', 'CUS-007', 'SITE-007', 'SVC-001', 'Panchkula', 215000, 148000, 12, 'On Hold', '2026-11-12'],
    ['PRJ-008', 'Campus Wi-Fi Setup', 'CUS-008', 'SITE-008', 'SVC-005', 'Ambala', 248000, 170000, 100, 'Completed', '2026-09-18']
  ];
  put('projects', projectData.map(([id, name, customer, site, service, city, value, estimatedCost, progress, status, dueDate], index) => ({ id: String(id), name, customer, site, service, city, value, estimatedCost, progress, status, dueDate, paymentDueDate: dueDate, startDate: index > 4 ? '2026-08-15' : '2026-09-15', manager: 'EMP-003', salesperson: 'EMP-002', technicians: [index % 2 ? 'EMP-008' : 'EMP-004'], priority: index === 4 ? 'High' : 'Normal', type: name, department: index === 2 ? 'Web Development' : 'Technical', notes: 'Demo project: linked costs, payments and material update its financial summary.', ...(status === 'Completed' ? { completedDate: dueDate } : {}) })));
  const leadNames = ['CityCare Clinic', 'Urban Cafe', 'Northstar Logistics', 'Bright Path School', 'Apex Realtors', 'Verma Traders', 'Kaur Enterprises', 'Singh Automobiles', 'Nimbus Co-working', 'Tricity Dental', 'Bluebird Academy', 'Metro Warehouse', 'Viva Beauty Studio', 'Evergreen Society', 'City Square Hotel', 'Zenith Manufacturing', 'Aarav Residency', 'Bansal Foods'];
  const leadStates = ['New', 'Contacted', 'Interested', 'Site Survey Required', 'Negotiation', 'Follow-up', 'Won', 'New', 'Requirement Gathering', 'Site Survey Completed', 'On Hold', 'Lost', 'New', 'Interested', 'Follow-up', 'Negotiation', 'Not Interested', 'Contacted'];
  put('leads', leadNames.map((name, index) => ({ id: `LEAD-${String(index + 1).padStart(3, '0')}`, name: ['Aman Verma', 'Simran Kaur', 'Rakesh Malhotra', 'Neha Bansal', 'Vikram Sethi'][index % 5], company: name, contactPerson: ['Aman Verma', 'Simran Kaur', 'Rakesh Malhotra', 'Neha Bansal', 'Vikram Sethi'][index % 5], mobile: `+91 98001 ${String(40000 + index)}`, email: `contact${index + 1}@example.com`, city: ['Ambala', 'Chandigarh', 'Mohali', 'Panchkula'][index % 4], address: `${index + 1}, Market Road`, source: ['Google Ads', 'Referral', 'Website', 'Meta Ads', 'Phone Call'][index % 5], type: 'Service', service: ['SVC-001', 'SVC-003', 'SVC-013', 'SVC-018', 'SVC-011'][index % 5], requirement: ['16-camera CCTV installation', 'Office LAN + Wi-Fi', 'Business website', 'Social media management', 'Managed IT support'][index % 5], budget: [125000, 240000, 95000, 72000, 48000][index % 5], assignedTo: 'EMP-002', priority: index % 3 === 0 ? 'High' : 'Normal', status: leadStates[index], lastContact: '2026-10-04', nextFollowup: index % 4 === 0 ? '2026-10-05' : '2026-10-07', expectedClosing: '2026-10-24', createdAt: index < 3 ? '2026-10-06T07:00:00.000Z' : '2026-10-02T08:00:00.000Z', ...(index === 6 ? { project: 'PRJ-003', customer: 'CUS-003' } : {}) })));
  put('followups', [
    { id: 'FU-001', name: 'Review camera placement with CityCare', lead: 'LEAD-001', type: 'Phone Call', assignedTo: 'EMP-002', dueAt: '2026-10-06T10:00', priority: 'High', status: 'Scheduled', comments: 'Ask for floor plan before site survey.' },
    { id: 'FU-002', name: 'Confirm networking budget', lead: 'LEAD-002', type: 'WhatsApp', assignedTo: 'EMP-002', dueAt: '2026-10-05T15:00', priority: 'High', status: 'Scheduled' },
    { id: 'FU-003', name: 'Website proposal review', lead: 'LEAD-003', type: 'Video Call', assignedTo: 'EMP-005', dueAt: '2026-10-07T11:30', priority: 'Normal', status: 'Scheduled' },
    { id: 'FU-004', name: 'Campus handover satisfaction call', customer: 'CUS-008', project: 'PRJ-008', type: 'Phone Call', assignedTo: 'EMP-002', dueAt: '2026-10-02T09:30', status: 'Completed', outcome: 'Customer happy with Wi-Fi coverage; AMC discussion next month.' }
  ]);
  put('opportunities', [{ id: 'OPP-001', name: 'ABC Retail · Annual CCTV Care', customer: 'CUS-001', service: 'SVC-002', value: 32000, probability: 75, assignedTo: 'EMP-002', closingDate: '2026-10-22', status: 'Negotiation' }]);
  put('inventory', products.map((product, index) => ({ id: `STK-${String(index + 1).padStart(3, '0')}`, name: `${product[2]} · Main Office`, product: product[0], location: 'Main Office', quantity: [124, 36, 48, 8, 86, 120, 210, 75, 2, 7][index], reserved: index === 0 ? 8 : index === 3 ? 2 : 0, damaged: 0, returned: 0, unitCost: product[7], notes: 'Opening demo stock snapshot.' })));
  store.inventory.push({ id: 'STK-011', name: '4MP IP Dome Camera · Warehouse', product: 'PROD-001', location: 'Warehouse', quantity: 40, reserved: 0, unitCost: 2450, demo: true });
  put('allocations', [
    { id: 'MAT-001', name: 'MAT-2026-104', product: 'PROD-001', project: 'PRJ-001', technician: 'EMP-004', location: 'Main Office', quantity: 24, usedQuantity: 16, returnedQuantity: 0, wastage: 0, estimatedQuantity: 24, date: '2026-10-02', approvalStatus: 'Approved', status: 'Issued' },
    { id: 'MAT-002', name: 'MAT-2026-105', product: 'PROD-004', project: 'PRJ-002', technician: 'EMP-008', location: 'Main Office', quantity: 8, usedQuantity: 6, returnedQuantity: 0, wastage: 0, estimatedQuantity: 8, date: '2026-10-03', approvalStatus: 'Approved', status: 'Used' }
  ]);
  put('stockTransfers', [{ id: 'TRF-001', name: 'TRF-2026-026', product: 'PROD-001', fromLocation: 'Warehouse', toLocation: 'Main Office', quantity: 12, date: '2026-10-07', assignedTo: 'EMP-009', status: 'Draft', notes: 'Restock the installation team for next week.' }]);
  put('purchaseRequests', [{ id: 'REQ-001', name: 'REQ-2026-018', project: 'PRJ-005', product: 'PROD-009', quantity: 5, requestedBy: 'EMP-004', requiredBy: '2026-10-09', priority: 'High', approvalStatus: 'Pending', status: 'Requested' }]);
  put('purchaseOrders', [{ id: 'PO-001', name: 'PO-2026-041', supplier: 'SUP-002', project: 'PRJ-005', product: 'PROD-009', quantity: 5, rate: 5200, gstRate: 18, orderDate: '2026-10-04', deliveryDate: '2026-10-09', location: 'Main Office', paymentTerms: '15 days', approvalStatus: 'Approved', status: 'Ordered' }]);
  put('purchases', [{ id: 'PUR-001', name: 'GRN-2026-036', supplier: 'SUP-001', product: 'PROD-001', quantity: 20, rate: 2450, gstRate: 18, date: '2026-09-28', location: 'Main Office', dueDate: '2026-10-28', status: 'Received', notes: 'Receipt is already included in the opening stock snapshot.' }]);
  put('supplierPayments', [{ id: 'SPAY-001', name: 'SUPPAY-2026-032', supplier: 'SUP-001', purchase: 'PUR-001', amount: 25000, date: '2026-10-01', method: 'Bank Transfer', status: 'Paid' }]);
  put('expenses', [
    ...projectData.map((p, index) => ({ id: `EXP-${String(index + 1).padStart(3, '0')}`, name: `${p[1]} · Labour & delivery`, date: index > 4 ? '2026-09-20' : '2026-10-03', category: 'Labour', amount: [116800, 176000, 42000, 54000, 22000, 43000, 8000, 154000][index], project: p[0], employee: index % 2 ? 'EMP-008' : 'EMP-004', method: 'Bank Transfer', approvalStatus: 'Approved', status: 'Paid', notes: 'Approved demo delivery expenditure.' })),
    { id: 'EXP-009', name: 'Office rent · October', date: '2026-10-01', category: 'Rent', amount: 28000, method: 'Bank Transfer', approvalStatus: 'Approved', status: 'Paid' },
    { id: 'EXP-010', name: 'Google Ads · October acquisition', date: '2026-10-04', category: 'Advertising', amount: 18500, method: 'Credit Card', approvalStatus: 'Approved', status: 'Paid' },
    { id: 'EXP-011', name: 'On-site travel reimbursement', date: '2026-10-05', category: 'Travel', amount: 1850, project: 'PRJ-001', employee: 'EMP-004', method: 'UPI', approvalStatus: 'Pending', status: 'Submitted' },
    ...['2026-05-15', '2026-06-15', '2026-07-15', '2026-08-15', '2026-09-15'].map((date, i) => ({ id: `EXP-H0${i + 1}`, name: `Office operations · ${date.slice(0, 7)}`, date, category: 'Miscellaneous', amount: [34000, 38000, 42000, 49000, 55000][i], approvalStatus: 'Approved', status: 'Paid', method: 'Bank Transfer' }))
  ]);
  put('payments', [
    { id: 'PAY-001', name: 'ABC Retail · Installation advance', customer: 'CUS-001', project: 'PRJ-001', amount: 142500, date: '2026-10-02', type: 'Advance', method: 'Bank Transfer', transactionId: 'DEMO-UTR-1041', status: 'Received' },
    { id: 'PAY-002', name: 'Axis Industries · Phase 1', customer: 'CUS-002', project: 'PRJ-002', amount: 180000, date: '2026-09-22', type: 'Partial', method: 'Bank Transfer', status: 'Received' },
    { id: 'PAY-003', name: 'Kaur Hospital · Website advance', customer: 'CUS-003', project: 'PRJ-003', amount: 82500, date: '2026-10-03', type: 'Advance', method: 'UPI', status: 'Received' },
    { id: 'PAY-004', name: 'GreenLeaf · Campaign retainer', customer: 'CUS-004', project: 'PRJ-004', amount: 72000, date: '2026-10-01', type: 'Partial', method: 'Bank Transfer', status: 'Received' },
    { id: 'PAY-005', name: 'Malhotra · Network advance', customer: 'CUS-005', project: 'PRJ-005', amount: 90000, date: '2026-09-28', type: 'Advance', method: 'Cheque', status: 'Received' },
    { id: 'PAY-006', name: 'Sethi · Support settlement', customer: 'CUS-006', project: 'PRJ-006', amount: 96000, date: '2026-09-25', type: 'Balance', method: 'Bank Transfer', status: 'Received' },
    { id: 'PAY-007', name: 'Bansal · Booking advance', customer: 'CUS-007', project: 'PRJ-007', amount: 45000, date: '2026-08-25', type: 'Advance', method: 'UPI', status: 'Received' },
    { id: 'PAY-008', name: 'Sunrise · Campus installation', customer: 'CUS-008', project: 'PRJ-008', amount: 248000, date: '2026-09-18', type: 'Balance', method: 'Bank Transfer', status: 'Received' }
  ]);
  put('income', ['2026-05-12', '2026-06-12', '2026-07-12', '2026-08-12', '2026-09-12'].map((date, i) => ({ id: `INC-00${i + 1}`, name: `One-time IT support · ${date.slice(0, 7)}`, customer: 'CUS-006', service: 'SVC-011', amount: [98000, 115000, 126000, 138000, 148000][i], date, method: 'Bank Transfer', status: 'Received' })));
  put('receivables', [{ id: 'REC-001', name: 'Ad-hoc recovery support', customer: 'CUS-005', amount: 12000, paid: 5000, dueDate: '2026-09-30', followupNotes: 'Accounts team to call on Tuesday.', status: 'Partially Paid' }]);
  put('payables', [{ id: 'DUE-001', name: 'September fiber splicing contractor', supplier: 'SUP-002', amount: 18000, paid: 0, dueDate: '2026-10-10', status: 'Unpaid' }]);
  put('tasks', [
    { id: 'TASK-001', name: 'Camera placement and testing', project: 'PRJ-001', assignedTo: 'EMP-004', dueDate: '2026-10-08', priority: 'High', status: 'In Progress', progress: 75, estimatedHours: 12, actualHours: 8, checklist: 'Verify camera angle\nTest night vision\nRecord serial numbers\nLabel cabling', startDate: '2026-10-04' },
    { id: 'TASK-002', name: 'Document VLAN and firewall rules', project: 'PRJ-002', assignedTo: 'EMP-008', dueDate: '2026-10-12', priority: 'Normal', status: 'To Do', progress: 0, estimatedHours: 6 },
    { id: 'TASK-003', name: 'Homepage design review', project: 'PRJ-003', assignedTo: 'EMP-005', dueDate: '2026-10-09', priority: 'Normal', status: 'In Progress', progress: 60, estimatedHours: 10, actualHours: 6 },
    { id: 'TASK-004', name: 'Approve October content creatives', project: 'PRJ-004', assignedTo: 'EMP-006', dueDate: '2026-10-07', priority: 'High', status: 'Blocked', progress: 90, comments: 'Waiting for client brand approval.' }
  ]);
  put('surveys', [{ id: 'SUR-001', name: 'Bright Path · CCTV & Wi-Fi survey', lead: 'LEAD-004', surveyDate: '2026-10-07', technician: 'EMP-004', requirement: 'Secure entrance, corridors and school grounds. Wi-Fi for administration.', floors: 3, rooms: 24, existingNetwork: 'Legacy unmanaged switch', existingCctv: '8 analog cameras', existingInternet: '100 Mbps fiber', existingRack: '6U wall rack', existingCabling: 'CAT5e', power: 'Available', ups: '650VA desktop UPS', challenges: 'Outdoor cable runs require conduit.', cableLength: 480, devices: '12 IP cameras, 2 PoE switches, 4 APs', labour: '2 technicians', estimatedHours: 20, status: 'Scheduled' }]);
  put('workOrders', [
    { id: 'WO-001', name: 'WO-2026-104', customer: 'CUS-001', site: 'SITE-001', project: 'PRJ-001', technician: 'EMP-004', description: 'Install final 8 IP cameras and verify recording.', products: ['PROD-001', 'PROD-002'], services: ['SVC-001'], tools: 'Drill, crimper, cable tester, ladder', estimatedHours: 6, scheduledAt: '2026-10-06T09:30', priority: 'High', status: 'In Progress' },
    { id: 'WO-002', name: 'WO-2026-105', customer: 'CUS-002', site: 'SITE-002', project: 'PRJ-002', technician: 'EMP-008', description: 'Test VLAN connectivity and wireless coverage.', products: ['PROD-003', 'PROD-004'], services: ['SVC-003'], estimatedHours: 4, scheduledAt: '2026-10-06T11:00', priority: 'Normal', status: 'Scheduled' },
    { id: 'WO-003', name: 'WO-2026-106', customer: 'CUS-004', site: 'SITE-004', technician: 'EMP-004', description: 'Quarterly AMC maintenance inspection.', estimatedHours: 2, scheduledAt: '2026-10-07T13:00', priority: 'Normal', status: 'Scheduled' }
  ]);
  put('technicianJobs', [
    { id: 'JOB-001', name: 'Final camera installation', workOrder: 'WO-001', project: 'PRJ-001', customer: 'CUS-001', site: 'SITE-001', technician: 'EMP-004', scheduledAt: '2026-10-06T09:30', status: 'Work Started', instructions: 'Coordinate store access with Aman. Record all installed serial numbers.', equipment: 'Drill, CAT6 tester, ladder', allocation: 'MAT-001', navigationUrl: 'https://maps.google.com/?q=Ambala', notes: 'Reached site at 09:20.' },
    { id: 'JOB-002', name: 'LAN acceptance testing', workOrder: 'WO-002', project: 'PRJ-002', customer: 'CUS-002', site: 'SITE-002', technician: 'EMP-008', scheduledAt: '2026-10-06T11:00', status: 'Assigned', instructions: 'Validate every network port. Upload test report.', allocation: 'MAT-002', navigationUrl: 'https://maps.google.com/?q=Chandigarh' }
  ]);
  put('assets', [
    { id: 'ASSET-001', name: 'ABC Retail · Entrance Camera', customer: 'CUS-001', site: 'SITE-001', project: 'PRJ-001', product: 'PROD-001', brand: 'Hikvision', model: 'DS-2CD2143', serialNumber: 'DEMO-HIK-2026-001', macAddress: '02:00:00:10:00:01', ipAddress: '192.168.10.11', installationDate: '2026-10-02', warrantyExpiry: '2028-10-02', supplier: 'SUP-001', purchaseDate: '2026-09-28', purchasePrice: 2450, sellingPrice: 3800, status: 'Active' },
    { id: 'ASSET-002', name: 'Axis · Core Router', customer: 'CUS-002', site: 'SITE-002', project: 'PRJ-002', product: 'PROD-003', brand: 'TP-Link', model: 'Archer AX23', serialNumber: 'DEMO-TPL-2026-002', macAddress: '02:00:00:20:00:01', ipAddress: '192.168.20.1', installationDate: '2026-09-25', warrantyExpiry: '2028-09-25', supplier: 'SUP-002', purchasePrice: 3100, sellingPrice: 4600, status: 'Active' }
  ]);
  put('serials', store.assets.map((asset, index) => ({ id: `SER-00${index + 1}`, name: asset.serialNumber, type: 'Serial Number', product: asset.product, supplier: asset.supplier, customer: asset.customer, site: asset.site, project: asset.project, asset: asset.id, location: 'Customer Site', installationDate: asset.installationDate, warrantyExpiry: asset.warrantyExpiry, status: 'Installed' })));
  put('networks', [{ id: 'NET-001', name: 'Axis · Core Router', customer: 'CUS-002', site: 'SITE-002', asset: 'ASSET-002', type: 'Router', ipAddress: '192.168.20.1', vlans: '10 · Office\n20 · Guest\n30 · CCTV', isp: 'Business fiber · 300 Mbps', wanIp: '203.0.113.10', lanRange: '192.168.20.0/24', rack: '12U communications rack', firmware: '1.2.4', status: 'Active', configuration: 'Guest network isolated. Management allowed from VLAN 10.', credentialRef: 'VAULT-001' }]);
  put('cctv', [{ id: 'CCTV-001', name: 'Entrance · Camera 01', customer: 'CUS-001', site: 'SITE-001', location: 'Main entrance', cameraNumber: 'CAM-01', ipAddress: '192.168.10.11', type: 'IP Camera', channel: 1, hdd: '4 TB', recordingDays: 30, installationDate: '2026-10-02', warrantyExpiry: '2028-10-02', serialNumber: 'DEMO-HIK-2026-001', status: 'Active' }]);
  put('websites', [{ id: 'WEB-001', name: 'Kaur Hospital Website', project: 'PRJ-003', customer: 'CUS-003', domain: 'kaurhospital.example.com', hosting: 'HOST-001', cms: 'WordPress', hostingProvider: 'Managed Cloud Hosting', domainProvider: 'Example Registrar', sslExpiry: '2027-09-30', theme: 'Custom hospital theme', plugins: 'Forms, SEO, backups', developer: 'EMP-005', clientContact: 'CON-003', status: 'Design', pages: 'Home\nAbout\nDepartments\nDoctors\nAppointments\nContact', features: 'Appointment request, doctor directory, mobile accessibility', contentStatus: 'Awaiting doctor profiles', approvals: 'Sitemap approved', revisions: 'Use more hospital photography.', launchDate: '2026-10-30' }]);
  put('socialAccounts', [{ id: 'SOC-001', name: 'GreenLeaf · Instagram', customer: 'CUS-004', platform: 'Instagram', profileUrl: 'https://instagram.com/', postingFrequency: '4 posts + 2 reels each week', monthlyPackage: 18000, assignedTo: 'EMP-006', status: 'Active' }]);
  put('content', [
    { id: 'POST-001', name: 'World Mental Health Day', customer: 'CUS-004', account: 'SOC-001', postDate: '2026-10-10', type: 'Carousel', caption: 'Your wellbeing deserves care. Book a consultation with our specialists.', status: 'Client Approval', clientApproval: false, assignedTo: 'EMP-006', scheduledAt: '2026-10-10T09:00', campaign: 'AD-001' },
    { id: 'POST-002', name: 'Meet our cardiology team', customer: 'CUS-004', account: 'SOC-001', postDate: '2026-10-08', type: 'Reel', status: 'Approved', clientApproval: true, assignedTo: 'EMP-006', scheduledAt: '2026-10-08T18:00' }
  ]);
  put('campaigns', [{ id: 'AD-001', name: 'GreenLeaf · Preventive Health', customer: 'CUS-004', platform: 'Meta Ads', objective: 'Consultation leads', startDate: '2026-10-01', endDate: '2026-10-31', budget: 30000, dailyBudget: 1000, targetLocation: 'Panchkula + 15 km', audience: 'Adults 25–55, health and wellbeing', landingPage: 'https://greenleaf.example.com/health', spend: 6500, impressions: 48200, reach: 29400, clicks: 780, leadCount: 42, conversions: 8, conversionRevenue: 28000, status: 'Active' }]);
  put('amc', [
    { id: 'AMC-001', name: 'GreenLeaf · CCTV Care 2026', customer: 'CUS-004', site: 'SITE-004', system: '24-camera CCTV system', startDate: '2025-10-20', endDate: '2026-10-20', amount: 36000, visits: 4, visitsCompleted: 3, technician: 'EMP-004', status: 'Due Soon', notes: 'Renewal conversation scheduled for 14 October.' },
    { id: 'AMC-002', name: 'Axis · Network Maintenance', customer: 'CUS-002', site: 'SITE-002', system: 'Office LAN, Wi-Fi and firewall', startDate: '2026-04-01', endDate: '2027-03-31', amount: 48000, visits: 6, visitsCompleted: 3, technician: 'EMP-008', status: 'Active' }
  ]);
  put('licenses', [{ id: 'LIC-001', name: 'Sethi · Microsoft 365 Business', customer: 'CUS-006', type: 'Microsoft 365', users: 15, startDate: '2025-10-13', expiryDate: '2026-10-13', supplier: 'SUP-003', purchasePrice: 72000, sellingPrice: 90000, assignedTo: 'EMP-002', status: 'Due Soon', keyRef: 'VAULT-002' }, { id: 'LIC-002', name: 'ABC Retail · Antivirus', customer: 'CUS-001', product: 'PROD-008', type: 'Antivirus', users: 5, startDate: '2026-06-01', expiryDate: '2027-05-31', supplier: 'SUP-003', purchasePrice: 3200, sellingPrice: 5500, assignedTo: 'EMP-002', status: 'Active' }]);
  put('domains', [{ id: 'DOM-001', name: 'kaurhospital.example.com', customer: 'CUS-003', registrar: 'Example Registrar', registrationDate: '2025-10-28', expiryDate: '2026-10-28', renewalAmount: 1400, hosting: 'HOST-001', status: 'Due Soon' }]);
  put('hosting', [{ id: 'HOST-001', name: 'Kaur Hospital · Managed Hosting', customer: 'CUS-003', provider: 'Managed Cloud Hosting', plan: 'Business 20 GB', startDate: '2026-01-01', expiryDate: '2026-12-31', sslExpiry: '2026-10-17', renewalAmount: 9600, status: 'Active' }]);
  put('recurring', [{ id: 'RR-001', name: 'GreenLeaf · Social media retainer', customer: 'CUS-004', service: 'SVC-018', cycle: 'Monthly', amount: 18000, startDate: '2026-04-01', renewalDate: '2026-11-01', status: 'Active' }, { id: 'RR-002', name: 'Axis · Network AMC', customer: 'CUS-002', service: 'SVC-003', cycle: 'Annual', amount: 48000, startDate: '2026-04-01', renewalDate: '2027-03-31', status: 'Active' }, { id: 'RR-003', name: 'Kaur · Website maintenance', customer: 'CUS-003', service: 'SVC-014', cycle: 'Monthly', amount: 4500, startDate: '2026-11-01', renewalDate: '2026-12-01', status: 'Active' }]);
  put('tickets', [{ id: 'TKT-001', name: 'IT-2026-085', customer: 'CUS-001', site: 'SITE-001', issue: 'Camera 4 intermittently loses connection', category: 'CCTV', priority: 'High', technician: 'EMP-004', status: 'Working', createdDate: '2026-10-05', dueDate: '2026-10-06', resolution: '' }, { id: 'TKT-002', name: 'IT-2026-086', customer: 'CUS-002', site: 'SITE-002', issue: 'Guest Wi-Fi password rotation requested', category: 'Networking', priority: 'Normal', technician: 'EMP-008', status: 'Assigned', createdDate: '2026-10-06', dueDate: '2026-10-08' }, { id: 'TKT-003', name: 'IT-2026-083', customer: 'CUS-006', site: 'SITE-006', issue: 'Outlook email profile configuration', category: 'Software', priority: 'Normal', technician: 'EMP-008', status: 'Resolved', createdDate: '2026-10-03', dueDate: '2026-10-04', resolution: 'Recreated profile and verified mailbox synchronization.' }]);
  put('remoteSupport', [{ id: 'REMOTE-001', name: 'Sethi · Outlook configuration', customer: 'CUS-006', ticket: 'TKT-003', technician: 'EMP-008', method: 'AnyDesk', issue: 'Outlook profile not synchronizing', startTime: '2026-10-03T11:00', endTime: '2026-10-03T11:45', solution: 'New mail profile configured; test messages received.', status: 'Completed' }]);
  put('warranties', [{ id: 'WAR-001', name: 'ABC Entrance Camera Warranty', product: 'PROD-001', customer: 'CUS-001', site: 'SITE-001', asset: 'ASSET-001', serialNumber: 'DEMO-HIK-2026-001', startDate: '2026-10-02', endDate: '2028-10-02', supplier: 'SUP-001', type: 'Manufacturer', status: 'Active' }]);
  put('rma', [{ id: 'RMA-001', name: 'RMA-2026-014', customer: 'CUS-001', site: 'SITE-001', product: 'PROD-001', serialNumber: 'DEMO-HIK-2025-021', supplier: 'SUP-001', fault: 'Camera fails to power through tested PoE port.', submissionDate: '2026-10-02', status: 'Sent to Supplier', notes: 'Supplier diagnostic result expected by 9 October.' }]);
  put('attendance', store.employees.map((employee, index) => ({ id: `ATT-00${index + 1}`, name: `${employee.name} · 6 Oct`, employee: employee.id, date: '2026-10-06', status: employee.role === 'Technician' ? 'Site Duty' : 'Present', checkIn: index % 2 ? '09:05' : '09:00', ...(employee.role === 'Technician' ? { site: employee.id === 'EMP-004' ? 'SITE-001' : 'SITE-002' } : {}) })));
  put('payroll', [{ id: 'SAL-001', name: 'Karan Singh · September 2026', employee: 'EMP-004', month: '2026-09', salary: 32000, bonus: 2000, incentives: 1500, deductions: 0, advances: 1000, reimbursements: 2200, status: 'Paid', paymentDate: '2026-10-01' }]);
  put('employeeExpenses', [{ id: 'CLAIM-001', name: 'Karan · Site travel', employee: 'EMP-004', project: 'PRJ-001', date: '2026-10-05', category: 'Petrol', amount: 950, reviewer: 'EMP-003', status: 'Manager Review', notes: 'Ambala site travel, 62 km.' }]);
  put('commissions', [{ id: 'COM-001', name: 'Sunrise Campus · Sales commission', salesperson: 'EMP-002', project: 'PRJ-008', revenue: 248000, type: 'Percentage', percentage: 2, status: 'Approved', date: '2026-10-01' }]);
  put('events', [{ id: 'EVT-001', name: 'Weekly delivery sync', type: 'Internal Meeting', startAt: '2026-10-06T16:30', endAt: '2026-10-06T17:00', assignedTo: 'EMP-003', location: 'ITSSS Main Office', status: 'Scheduled' }, { id: 'EVT-002', name: 'GreenLeaf · Content review', type: 'Meeting', startAt: '2026-10-07T12:00', endAt: '2026-10-07T12:30', customer: 'CUS-004', assignedTo: 'EMP-006', status: 'Scheduled' }]);
  put('notifications', []);
  put('documents', []);
  put('notes', [{ id: 'NOTE-001', name: 'ABC Retail installation access', content: 'Store manager can provide access before opening at 08:30. Keep the entrance camera angle clear of the illuminated sign.', type: 'Pinned', relatedModule: 'projects', relatedId: 'PRJ-001', author: 'EMP-003', date: '2026-10-04' }]);
  put('communication', [{ id: 'MSG-001', name: 'ABC Retail · Installation progress', customer: 'CUS-001', project: 'PRJ-001', channel: 'Email', recipient: 'billing@abcretail.example.com', message: 'Your installation is 80% complete. Final commissioning is scheduled for 15 October.', date: '2026-10-06T10:00', status: 'Draft' }]);
  const roleNames = ['Super Admin', 'Admin', 'Manager', 'Sales', 'Technician', 'Developer', 'Marketing', 'Accounts', 'Inventory', 'Viewer', 'Client'];
  put('roles', roleNames.map((name, index) => ({ id: `ROLE-${String(index + 1).padStart(3, '0')}`, name, description: `${name} workspace access`, permissions: name === 'Viewer' || name === 'Client' ? ['View', 'Download'] : name === 'Technician' ? ['View', 'Add', 'Edit', 'Download'] : ['View', 'Add', 'Edit', 'Delete', 'Export', 'Approve', 'Assign', 'Download', 'Share'], allowedModules: ['Super Admin', 'Admin', 'Manager'].includes(name) ? '*' : name === 'Sales' ? 'leads,followups,customers,contacts,opportunities,projects,events,documents,notes' : name === 'Technician' ? 'technicianJobs,workOrders,sites,tasks,assets,networks,cctv,tickets,remoteSupport,allocations,events,documents,notes,employees,products,services,customers,contacts,projects,attendance' : name === 'Developer' ? 'websites,projects,tasks,domains,hosting,events,documents,notes' : name === 'Marketing' ? 'socialAccounts,content,campaigns,customers,projects,tasks,events,documents,notes' : name === 'Accounts' ? 'projects,payments,expenses,income,receivables,payables,purchases,supplierPayments,payroll,employeeExpenses,commissions,documents' : name === 'Inventory' ? 'products,inventory,stockTransfers,allocations,serials,stockHistory,suppliers,purchaseRequests,purchaseOrders,purchases' : name === 'Client' ? 'projects,payments,tickets,assets,amc,licenses,documents,sites,customers,contacts' : '*', hiddenFields: ['Technician', 'Developer', 'Marketing', 'Sales', 'Client'].includes(name) ? 'projects.actualCost,projects.estimatedCost,projects.profit,projects.margin,projects.materialCost,projects.costVariance,products.purchasePrice,assets.purchasePrice,licenses.purchasePrice,employees.salary' : '', status: 'Active' })));
  put('users', [{ id: 'USER-001', name: 'Rohit Sharma', email: 'rohit@example.com', employee: 'EMP-001', role: 'ROLE-001', status: 'Active', twoFactor: false }, { id: 'USER-002', name: 'Karan Singh', email: 'karan@example.com', employee: 'EMP-004', technician: 'EMP-004', role: 'ROLE-005', status: 'Active' }, { id: 'USER-003', name: 'ABC Retail Client', email: 'billing@abcretail.example.com', customer: 'CUS-001', role: 'ROLE-011', status: 'Active' }]);
  put('customFields', [{ id: 'FIELD-001', name: 'Preferred contact time', moduleId: 'leads', key: 'preferredContactTime', type: 'time', required: false, status: 'Active' }]);
  put('customModules', []);
  put('customStatuses', [{ id: 'STATUS-001', name: 'Awaiting Site Access', moduleId: 'projects', color: '#f59e0b', order: 11, terminal: false, status: 'Active' }]);
  put('customForms', [{ id: 'FORM-001', name: 'CCTV Installation Checklist', moduleId: 'technicianJobs', description: 'On-site completion and handover evidence.', fieldKeys: 'name,project,site,technician,status,serialNumbers,afterPhotos,signature,notes', instructions: 'Verify recording, label devices and collect customer acceptance.', status: 'Published' }]);
  put('categories', ['Ambala', 'Chandigarh', 'Panchkula', 'Mohali', 'Main Office', 'Warehouse'].map((name, index) => ({ id: `CAT-00${index + 1}`, name, type: index < 4 ? 'City' : 'Location', status: 'Active' })));
  put('taxes', [0, 5, 12, 18, 28].map((rate, index) => ({ id: `TAX-00${index + 1}`, name: `GST ${rate}%`, rate, status: 'Active' })));
  put('templates', [{ id: 'TMP-001', name: 'ITSSS Standard Work Order', type: 'Work Order', header: 'ITSSS · IT Smart Solution and Services', body: 'Please verify site access and material availability before starting work. Record serial numbers and customer acceptance before completion.', footer: 'Technology. People. Smarter Business.', status: 'Active' }]);
  put('automations', [{ id: 'AUTO-001', name: 'Convert won lead to project', trigger: 'Lead Won', action: 'Create Project', enabled: true }, { id: 'AUTO-002', name: 'Customer satisfaction after completion', trigger: 'Project Completed', action: 'Create Follow-up', daysBefore: 3, enabled: true }, { id: 'AUTO-003', name: 'AMC renewal pipeline · 30 days', trigger: 'AMC Expiring', action: 'Create Renewal Lead', daysBefore: 30, assignedTo: 'EMP-002', enabled: true }, { id: 'AUTO-004', name: 'Software renewal reminder · 7 days', trigger: 'License Expiring', action: 'Notify', daysBefore: 7, assignedTo: 'EMP-002', enabled: true }]);
  put('settings', [{ id: 'SET-001', name: 'ITSSS', address: 'Tricity, Chandigarh · India', mobile: '+91 98760 10001', email: 'hello@itsss.example.com', website: 'https://itsss.example.com', brandColor: '#087bf5', theme: 'Light', sessionMinutes: 60, passwordMinLength: 12, currency: 'INR' }]);
  put('savedViews', [{ id: 'VIEW-001', name: 'Hot leads in Tricity', moduleId: 'leads', search: '', filters: '{"priority":"High"}', columns: 'name,company,city,budget,status,nextFollowup', shared: true, employee: 'EMP-002' }]);
  put('vault', [{ id: 'VAULT-001', name: 'Axis · Router administration', customer: 'CUS-002', site: 'SITE-002', type: 'Router', reference: 'Organization password manager / Axis / Core Router', username: 'network-admin', owner: 'EMP-003', allowedRoles: 'Super Admin,Admin,Manager,Technician', notes: 'Reference only. No password is stored in this application.' }, { id: 'VAULT-002', name: 'Sethi · Microsoft 365 License', customer: 'CUS-006', type: 'License', reference: 'Organization password manager / Sethi / Microsoft 365', owner: 'EMP-007', allowedRoles: 'Super Admin,Admin,Accounts', notes: 'License key is stored in the external secure vault.' }]);
  put('backups', []);
  put('activities', [{ id: 'ACT-001', name: 'Karan reached ABC Retail site', module: 'technicianJobs', recordId: 'JOB-001', action: 'Technician Update', actor: 'Karan Singh', date: '2026-10-06T04:00:00.000Z', details: 'Job status changed to Work Started.' }, { id: 'ACT-002', name: 'Kaur Hospital advance received', module: 'payments', recordId: 'PAY-003', action: 'Payment Added', actor: 'Vikram Sethi', date: '2026-10-03T06:30:00.000Z', details: '₹82,500 received by UPI.' }]);
  put('stockHistory', [{ id: 'MOV-001', name: 'MAT-2026-104 · Issued to ABC Retail', product: 'PROD-001', location: 'Main Office', quantity: -16, reservedDelta: 8, type: 'Allocation', sourceModule: 'allocations', sourceId: 'MAT-001', date: '2026-10-02T06:00:00.000Z', actor: 'Ritika Gupta' }, { id: 'MOV-002', name: 'MAT-2026-105 · Axis installation', product: 'PROD-004', location: 'Main Office', quantity: -6, reservedDelta: 2, type: 'Allocation', sourceModule: 'allocations', sourceId: 'MAT-002', date: '2026-10-03T06:00:00.000Z', actor: 'Ritika Gupta' }]);
  put('auditLogs', [{ id: 'AUD-001', name: 'Demo workspace initialized', actor: 'System', action: 'Created', module: 'settings', recordId: 'SET-001', date: '2026-10-01T09:00:00.000Z', device: 'Demo initializer', ip: 'Unavailable', oldValue: '', newValue: 'Illustrative demo records initialized.' }]);
  return recalculate(store, new Date('2026-10-06T09:00:00Z'));
}
